
# This file is automatically generated, you probably don't want to edit this

descDistancesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "descDistancesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varDst = NULL,
            dstCoR = "columns",
            dstStd = "none",
            dstCtg = "ctgCnt",
            dstCnt = "euclid",
            pwrCnt = 2,
            rt_Cnt = 2,
            dstFrq = "chisq",
            dstBnM = "jaccards",
            p__BnM = "1",
            np_BnM = "0",
            dstBnC = "k2",
            p__BnC = "1",
            np_BnC = "0",
            dstBnP = "q",
            p__BnP = "1",
            np_BnP = "0",
            dstBnO = "bseuclid",
            p__BnO = "1",
            np_BnO = "0",
            shwHlp = FALSE,
            jxfLog = FALSE, ...) {

            super$initialize(
                package="jTransform",
                name="descDistances",
                requiresData=TRUE,
                ...)

            private$..varDst <- jmvcore::OptionVariables$new(
                "varDst",
                varDst,
                permitted=list(
                    "numeric",
                    "factor"),
                required=TRUE,
                default=NULL)
            private$..dstCoR <- jmvcore::OptionList$new(
                "dstCoR",
                dstCoR,
                options=list(
                    "columns",
                    "rows"),
                default="columns")
            private$..dstStd <- jmvcore::OptionList$new(
                "dstStd",
                dstStd,
                options=list(
                    "none",
                    "z",
                    "sd",
                    "range",
                    "max",
                    "mean",
                    "rescale"),
                default="none")
            private$..dstCtg <- jmvcore::OptionList$new(
                "dstCtg",
                dstCtg,
                options=list(
                    "ctgCnt",
                    "ctgFrq",
                    "ctgBnM",
                    "ctgBnC",
                    "ctgBnP",
                    "ctgBnO",
                    "ctgNot"),
                default="ctgCnt")
            private$..dstCnt <- jmvcore::OptionList$new(
                "dstCnt",
                dstCnt,
                options=list(
                    "euclid",
                    "seuclid",
                    "block",
                    "cosine",
                    "correlation",
                    "chebychev",
                    "minkowski",
                    "power",
                    "canberra"),
                default="euclid")
            private$..pwrCnt <- jmvcore::OptionInteger$new(
                "pwrCnt",
                pwrCnt,
                default=2)
            private$..rt_Cnt <- jmvcore::OptionInteger$new(
                "rt_Cnt",
                rt_Cnt,
                default=2)
            private$..dstFrq <- jmvcore::OptionList$new(
                "dstFrq",
                dstFrq,
                options=list(
                    "chisq",
                    "ph2"),
                default="chisq")
            private$..dstBnM <- jmvcore::OptionList$new(
                "dstBnM",
                dstBnM,
                options=list(
                    "jaccards",
                    "jaccardd",
                    "sm",
                    "dice",
                    "rr",
                    "rt",
                    "ss1",
                    "ss2",
                    "ss3",
                    "k1"),
                default="jaccards")
            private$..p__BnM <- jmvcore::OptionString$new(
                "p__BnM",
                p__BnM,
                default="1")
            private$..np_BnM <- jmvcore::OptionString$new(
                "np_BnM",
                np_BnM,
                default="0")
            private$..dstBnC <- jmvcore::OptionList$new(
                "dstBnC",
                dstBnC,
                options=list(
                    "k2",
                    "hamann",
                    "ss4"),
                default="k2")
            private$..p__BnC <- jmvcore::OptionString$new(
                "p__BnC",
                p__BnC,
                default="1")
            private$..np_BnC <- jmvcore::OptionString$new(
                "np_BnC",
                np_BnC,
                default="0")
            private$..dstBnP <- jmvcore::OptionList$new(
                "dstBnP",
                dstBnP,
                options=list(
                    "q",
                    "lambda",
                    "y",
                    "d"),
                default="q")
            private$..p__BnP <- jmvcore::OptionString$new(
                "p__BnP",
                p__BnP,
                default="1")
            private$..np_BnP <- jmvcore::OptionString$new(
                "np_BnP",
                np_BnP,
                default="0")
            private$..dstBnO <- jmvcore::OptionList$new(
                "dstBnO",
                dstBnO,
                options=list(
                    "bseuclid",
                    "beuclid",
                    "phi",
                    "ochiai",
                    "pattern",
                    "bshape",
                    "disper",
                    "size",
                    "blwmn",
                    "variance",
                    "ss5"),
                default="bseuclid")
            private$..p__BnO <- jmvcore::OptionString$new(
                "p__BnO",
                p__BnO,
                default="1")
            private$..np_BnO <- jmvcore::OptionString$new(
                "np_BnO",
                np_BnO,
                default="0")
            private$..shwHlp <- jmvcore::OptionBool$new(
                "shwHlp",
                shwHlp,
                default=FALSE)
            private$..jxfLog <- jmvcore::OptionBool$new(
                "jxfLog",
                jxfLog,
                hidden=TRUE,
                default=FALSE)

            self$.addOption(private$..varDst)
            self$.addOption(private$..dstCoR)
            self$.addOption(private$..dstStd)
            self$.addOption(private$..dstCtg)
            self$.addOption(private$..dstCnt)
            self$.addOption(private$..pwrCnt)
            self$.addOption(private$..rt_Cnt)
            self$.addOption(private$..dstFrq)
            self$.addOption(private$..dstBnM)
            self$.addOption(private$..p__BnM)
            self$.addOption(private$..np_BnM)
            self$.addOption(private$..dstBnC)
            self$.addOption(private$..p__BnC)
            self$.addOption(private$..np_BnC)
            self$.addOption(private$..dstBnP)
            self$.addOption(private$..p__BnP)
            self$.addOption(private$..np_BnP)
            self$.addOption(private$..dstBnO)
            self$.addOption(private$..p__BnO)
            self$.addOption(private$..np_BnO)
            self$.addOption(private$..shwHlp)
            self$.addOption(private$..jxfLog)
        }),
    active = list(
        varDst = function() private$..varDst$value,
        dstCoR = function() private$..dstCoR$value,
        dstStd = function() private$..dstStd$value,
        dstCtg = function() private$..dstCtg$value,
        dstCnt = function() private$..dstCnt$value,
        pwrCnt = function() private$..pwrCnt$value,
        rt_Cnt = function() private$..rt_Cnt$value,
        dstFrq = function() private$..dstFrq$value,
        dstBnM = function() private$..dstBnM$value,
        p__BnM = function() private$..p__BnM$value,
        np_BnM = function() private$..np_BnM$value,
        dstBnC = function() private$..dstBnC$value,
        p__BnC = function() private$..p__BnC$value,
        np_BnC = function() private$..np_BnC$value,
        dstBnP = function() private$..dstBnP$value,
        p__BnP = function() private$..p__BnP$value,
        np_BnP = function() private$..np_BnP$value,
        dstBnO = function() private$..dstBnO$value,
        p__BnO = function() private$..p__BnO$value,
        np_BnO = function() private$..np_BnO$value,
        shwHlp = function() private$..shwHlp$value,
        jxfLog = function() private$..jxfLog$value),
    private = list(
        ..varDst = NA,
        ..dstCoR = NA,
        ..dstStd = NA,
        ..dstCtg = NA,
        ..dstCnt = NA,
        ..pwrCnt = NA,
        ..rt_Cnt = NA,
        ..dstFrq = NA,
        ..dstBnM = NA,
        ..p__BnM = NA,
        ..np_BnM = NA,
        ..dstBnC = NA,
        ..p__BnC = NA,
        ..np_BnC = NA,
        ..dstBnP = NA,
        ..p__BnP = NA,
        ..np_BnP = NA,
        ..dstBnO = NA,
        ..p__BnO = NA,
        ..np_BnO = NA,
        ..shwHlp = NA,
        ..jxfLog = NA)
)

descDistancesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "descDistancesResults",
    inherit = jmvcore::Group,
    active = list(
        genInf = function() private$.items[["genInf"]],
        dtaInf = function() private$.items[["dtaInf"]],
        pvwDta = function() private$.items[["pvwDta"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Distances / Proximities")
            self$add(jmvcore::Html$new(
                options=options,
                name="genInf",
                visible="(shwHlp)",
                clearWith=list(),
                content="Please assign the variables from the data set that should be included in the calculation of distances to \"Variables To Calculate Distances For\" and then select whether the distances are to be calculated between \"Columns\" or \"Rows\". You need at least two variables and two rows to calculate distances. Select then whether the input data are to be standardized (before calculating the distances) and which distance measure should be calculated.\n"))
            self$add(jmvcore::Html$new(
                options=options,
                name="dtaInf",
                clearWith=list(
                    "varDst",
                    "clmDst"),
                content=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="pvwDta",
                title="Distances / Proximities",
                refs=list(
                    "jTransform",
                    "jmvReadWrite"),
                clearWith=list(
                    "varDst",
                    "clmDst",
                    "stdDst",
                    "nmeDst"),
                rows=1,
                columns=list(
                    list(
                        `name`="fstCol", 
                        `title`=""))))}))

descDistancesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "descDistancesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "descDistances",
                version = c(1,0,0),
                options = options,
                results = descDistancesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Distances / Proximities
#'
#' 
#' @param data .
#' @param varDst .
#' @param dstCoR .
#' @param dstStd .
#' @param dstCtg .
#' @param dstCnt .
#' @param pwrCnt .
#' @param rt_Cnt .
#' @param dstFrq .
#' @param dstBnM .
#' @param p__BnM .
#' @param np_BnM .
#' @param dstBnC .
#' @param p__BnC .
#' @param np_BnC .
#' @param dstBnP .
#' @param p__BnP .
#' @param np_BnP .
#' @param dstBnO .
#' @param p__BnO .
#' @param np_BnO .
#' @param shwHlp .
#' @param jxfLog .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$genInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dtaInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pvwDta} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pvwDta$asDF}
#'
#' \code{as.data.frame(results$pvwDta)}
#'
#' @export
descDistances <- function(
    data,
    varDst = NULL,
    dstCoR = "columns",
    dstStd = "none",
    dstCtg = "ctgCnt",
    dstCnt = "euclid",
    pwrCnt = 2,
    rt_Cnt = 2,
    dstFrq = "chisq",
    dstBnM = "jaccards",
    p__BnM = "1",
    np_BnM = "0",
    dstBnC = "k2",
    p__BnC = "1",
    np_BnC = "0",
    dstBnP = "q",
    p__BnP = "1",
    np_BnP = "0",
    dstBnO = "bseuclid",
    p__BnO = "1",
    np_BnO = "0",
    shwHlp = FALSE,
    jxfLog = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("descDistances requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varDst)) varDst <- jmvcore::resolveQuo(jmvcore::enquo(varDst))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varDst), varDst, NULL))


    options <- descDistancesOptions$new(
        varDst = varDst,
        dstCoR = dstCoR,
        dstStd = dstStd,
        dstCtg = dstCtg,
        dstCnt = dstCnt,
        pwrCnt = pwrCnt,
        rt_Cnt = rt_Cnt,
        dstFrq = dstFrq,
        dstBnM = dstBnM,
        p__BnM = p__BnM,
        np_BnM = np_BnM,
        dstBnC = dstBnC,
        p__BnC = p__BnC,
        np_BnC = np_BnC,
        dstBnP = dstBnP,
        p__BnP = p__BnP,
        np_BnP = np_BnP,
        dstBnO = dstBnO,
        p__BnO = p__BnO,
        np_BnO = np_BnO,
        shwHlp = shwHlp,
        jxfLog = jxfLog)

    analysis <- descDistancesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

