
# This file is automatically generated, you probably don't want to edit this

descDistancesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "descDistancesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varDst = NULL,
            clmDst = "columns",
            stdDst = "none",
            nmeDst = "euclid",
            pwrDst = 2,
            rt_Dst = 2,
            p__Dst = "1",
            np_Dst = "0", ...) {

            super$initialize(
                package="jTransform",
                name="descDistances",
                requiresData=TRUE,
                ...)

            private$..varDst <- jmvcore::OptionVariables$new(
                "varDst",
                varDst,
                permitted=list(
                    "numeric",
                    "factor"),
                required=TRUE,
                default=NULL)
            private$..clmDst <- jmvcore::OptionList$new(
                "clmDst",
                clmDst,
                options=list(
                    "columns",
                    "rows"),
                default="columns")
            private$..stdDst <- jmvcore::OptionList$new(
                "stdDst",
                stdDst,
                options=list(
                    "none",
                    "z",
                    "sd",
                    "range",
                    "max",
                    "mean",
                    "rescale"),
                default="none")
            private$..nmeDst <- jmvcore::OptionList$new(
                "nmeDst",
                nmeDst,
                options=list(
                    "euclid",
                    "seuclid",
                    "block",
                    "canberra",
                    "chebychev",
                    "minkowski",
                    "power",
                    "cosine",
                    "correlation",
                    "chisq",
                    "ph2",
                    "rr",
                    "sm",
                    "jaccards",
                    "jaccardd",
                    "dice",
                    "rt",
                    "k1",
                    "ss1",
                    "ss2",
                    "ss3",
                    "k2",
                    "ss4",
                    "hamann",
                    "lambda",
                    "d",
                    "y",
                    "q",
                    "ochiai",
                    "ss5",
                    "phi",
                    "beuclid",
                    "bseuclid",
                    "size",
                    "pattern",
                    "bshape",
                    "disper",
                    "variance",
                    "blwmn",
                    "none"),
                default="euclid")
            private$..pwrDst <- jmvcore::OptionInteger$new(
                "pwrDst",
                pwrDst,
                default=2)
            private$..rt_Dst <- jmvcore::OptionInteger$new(
                "rt_Dst",
                rt_Dst,
                default=2)
            private$..p__Dst <- jmvcore::OptionString$new(
                "p__Dst",
                p__Dst,
                default="1")
            private$..np_Dst <- jmvcore::OptionString$new(
                "np_Dst",
                np_Dst,
                default="0")

            self$.addOption(private$..varDst)
            self$.addOption(private$..clmDst)
            self$.addOption(private$..stdDst)
            self$.addOption(private$..nmeDst)
            self$.addOption(private$..pwrDst)
            self$.addOption(private$..rt_Dst)
            self$.addOption(private$..p__Dst)
            self$.addOption(private$..np_Dst)
        }),
    active = list(
        varDst = function() private$..varDst$value,
        clmDst = function() private$..clmDst$value,
        stdDst = function() private$..stdDst$value,
        nmeDst = function() private$..nmeDst$value,
        pwrDst = function() private$..pwrDst$value,
        rt_Dst = function() private$..rt_Dst$value,
        p__Dst = function() private$..p__Dst$value,
        np_Dst = function() private$..np_Dst$value),
    private = list(
        ..varDst = NA,
        ..clmDst = NA,
        ..stdDst = NA,
        ..nmeDst = NA,
        ..pwrDst = NA,
        ..rt_Dst = NA,
        ..p__Dst = NA,
        ..np_Dst = NA)
)

descDistancesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "descDistancesResults",
    inherit = jmvcore::Group,
    active = list(
        genInf = function() private$.items[["genInf"]],
        pvwDta = function() private$.items[["pvwDta"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Distances / Proximities")
            self$add(jmvcore::Html$new(
                options=options,
                name="genInf",
                clearWith=list(
                    "varDst")))
            self$add(jmvcore::Table$new(
                options=options,
                name="pvwDta",
                title="Distances / Proximities",
                refs=list(
                    "jTransform",
                    "jmvReadWrite"),
                clearWith=list(
                    "varDst",
                    "clmDst",
                    "stdDst",
                    "nmeDst"),
                rows=1,
                columns=list(
                    list(
                        `name`="fstCol", 
                        `title`=""))))}))

descDistancesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "descDistancesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "descDistances",
                version = c(1,0,0),
                options = options,
                results = descDistancesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Distances / Proximities
#'
#' 
#' @param data .
#' @param varDst .
#' @param clmDst .
#' @param stdDst .
#' @param nmeDst .
#' @param pwrDst .
#' @param rt_Dst .
#' @param p__Dst .
#' @param np_Dst .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$genInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pvwDta} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pvwDta$asDF}
#'
#' \code{as.data.frame(results$pvwDta)}
#'
#' @export
descDistances <- function(
    data,
    varDst = NULL,
    clmDst = "columns",
    stdDst = "none",
    nmeDst = "euclid",
    pwrDst = 2,
    rt_Dst = 2,
    p__Dst = "1",
    np_Dst = "0") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("descDistances requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varDst)) varDst <- jmvcore::resolveQuo(jmvcore::enquo(varDst))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varDst), varDst, NULL))


    options <- descDistancesOptions$new(
        varDst = varDst,
        clmDst = clmDst,
        stdDst = stdDst,
        nmeDst = nmeDst,
        pwrDst = pwrDst,
        rt_Dst = rt_Dst,
        p__Dst = p__Dst,
        np_Dst = np_Dst)

    analysis <- descDistancesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

