
# This file is automatically generated, you probably don't want to edit this

jtAggregateOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtAggregateOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varAgg = NULL,
            grpAgg = NULL,
            clcN = FALSE,
            clcMss = FALSE,
            clcMn = FALSE,
            clcMdn = FALSE,
            clcMde = FALSE,
            clcSum = FALSE,
            clcSD = FALSE,
            clcVar = FALSE,
            clcRng = FALSE,
            clcMin = FALSE,
            clcMax = FALSE,
            clcIQR = FALSE,
            drpNA = TRUE,
            shwHlp = FALSE,
            jxfLog = FALSE, ...) {

            super$initialize(
                package="jTransform",
                name="jtAggregate",
                requiresData=TRUE,
                ...)

            private$..varAgg <- jmvcore::OptionVariables$new(
                "varAgg",
                varAgg)
            private$..grpAgg <- jmvcore::OptionVariables$new(
                "grpAgg",
                grpAgg)
            private$..clcN <- jmvcore::OptionBool$new(
                "clcN",
                clcN,
                default=FALSE)
            private$..clcMss <- jmvcore::OptionBool$new(
                "clcMss",
                clcMss,
                default=FALSE)
            private$..clcMn <- jmvcore::OptionBool$new(
                "clcMn",
                clcMn,
                default=FALSE)
            private$..clcMdn <- jmvcore::OptionBool$new(
                "clcMdn",
                clcMdn,
                default=FALSE)
            private$..clcMde <- jmvcore::OptionBool$new(
                "clcMde",
                clcMde,
                default=FALSE)
            private$..clcSum <- jmvcore::OptionBool$new(
                "clcSum",
                clcSum,
                default=FALSE)
            private$..clcSD <- jmvcore::OptionBool$new(
                "clcSD",
                clcSD,
                default=FALSE)
            private$..clcVar <- jmvcore::OptionBool$new(
                "clcVar",
                clcVar,
                default=FALSE)
            private$..clcRng <- jmvcore::OptionBool$new(
                "clcRng",
                clcRng,
                default=FALSE)
            private$..clcMin <- jmvcore::OptionBool$new(
                "clcMin",
                clcMin,
                default=FALSE)
            private$..clcMax <- jmvcore::OptionBool$new(
                "clcMax",
                clcMax,
                default=FALSE)
            private$..clcIQR <- jmvcore::OptionBool$new(
                "clcIQR",
                clcIQR,
                default=FALSE)
            private$..drpNA <- jmvcore::OptionBool$new(
                "drpNA",
                drpNA,
                default=TRUE)
            private$..shwHlp <- jmvcore::OptionBool$new(
                "shwHlp",
                shwHlp,
                default=FALSE)
            private$..btnCrt <- jmvcore::OptionAction$new(
                "btnCrt",
                FALSE,
                action="open")
            private$..jxfLog <- jmvcore::OptionBool$new(
                "jxfLog",
                jxfLog,
                hidden=TRUE,
                default=FALSE)

            self$.addOption(private$..varAgg)
            self$.addOption(private$..grpAgg)
            self$.addOption(private$..clcN)
            self$.addOption(private$..clcMss)
            self$.addOption(private$..clcMn)
            self$.addOption(private$..clcMdn)
            self$.addOption(private$..clcMde)
            self$.addOption(private$..clcSum)
            self$.addOption(private$..clcSD)
            self$.addOption(private$..clcVar)
            self$.addOption(private$..clcRng)
            self$.addOption(private$..clcMin)
            self$.addOption(private$..clcMax)
            self$.addOption(private$..clcIQR)
            self$.addOption(private$..drpNA)
            self$.addOption(private$..shwHlp)
            self$.addOption(private$..btnCrt)
            self$.addOption(private$..jxfLog)
        }),
    active = list(
        varAgg = function() private$..varAgg$value,
        grpAgg = function() private$..grpAgg$value,
        clcN = function() private$..clcN$value,
        clcMss = function() private$..clcMss$value,
        clcMn = function() private$..clcMn$value,
        clcMdn = function() private$..clcMdn$value,
        clcMde = function() private$..clcMde$value,
        clcSum = function() private$..clcSum$value,
        clcSD = function() private$..clcSD$value,
        clcVar = function() private$..clcVar$value,
        clcRng = function() private$..clcRng$value,
        clcMin = function() private$..clcMin$value,
        clcMax = function() private$..clcMax$value,
        clcIQR = function() private$..clcIQR$value,
        drpNA = function() private$..drpNA$value,
        shwHlp = function() private$..shwHlp$value,
        btnCrt = function() private$..btnCrt$value,
        jxfLog = function() private$..jxfLog$value),
    private = list(
        ..varAgg = NA,
        ..grpAgg = NA,
        ..clcN = NA,
        ..clcMss = NA,
        ..clcMn = NA,
        ..clcMdn = NA,
        ..clcMde = NA,
        ..clcSum = NA,
        ..clcSD = NA,
        ..clcVar = NA,
        ..clcRng = NA,
        ..clcMin = NA,
        ..clcMax = NA,
        ..clcIQR = NA,
        ..drpNA = NA,
        ..shwHlp = NA,
        ..btnCrt = NA,
        ..jxfLog = NA)
)

jtAggregateResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtAggregateResults",
    inherit = jmvcore::Group,
    active = list(
        fmtHTM = function() private$.items[["fmtHTM"]],
        genInf = function() private$.items[["genInf"]],
        dtaInf = function() private$.items[["dtaInf"]],
        pvwDta = function() private$.items[["pvwDta"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Aggregate")
            self$add(jmvcore::Html$new(
                options=options,
                name="fmtHTM",
                clearWith=list(),
                content="<style> #fmtHTM { display: none; } table { width: 100%; border-collapse: collapse; } th { background-color: #3e6da9; color: white; text-align: left; } tbody > td { border: 1px solid #ddd; padding: 8px; } tbody > tr:nth-child(even) { background-color: #d6eaf8; } tbody > tr:nth-child(odd) { background-color: #ffffff; } tbody > tr:hover { background-color: #aed6f1; } </style>\n"))
            self$add(jmvcore::Html$new(
                options=options,
                name="genInf",
                visible="(shwHlp)",
                clearWith=list(),
                content="Please assign the variables from the data set that should be aggregated to \"Variable(s) to Aggregate\" and grouping variables to \"Split By\" (e.g., if the aggregation were on the level of participants, the variable assigned to \"Split By\" would need to distinguish participants). The data need to be in long format (i.e., several rows per participant when using the example above). By setting the different check boxes, different aggregations can be requested, each resulting in a new column in the resulting data set.\n"))
            self$add(jmvcore::Html$new(
                options=options,
                name="dtaInf",
                clearWith=list(
                    "varAgg",
                    "grpAgg",
                    "clcN",
                    "clcMss",
                    "clcMn",
                    "clcMdn",
                    "clcMde",
                    "clcSum",
                    "clcSD",
                    "clcVar",
                    "clcRng",
                    "clcMin",
                    "clcMax",
                    "clcIQR",
                    "drpNA",
                    "btnCrt"),
                content=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="pvwDta",
                title="Data Preview",
                refs=list(
                    "jTransform",
                    "jmvReadWrite"),
                clearWith=list(
                    "varAgg",
                    "grpAgg",
                    "clcN",
                    "clcMss",
                    "clcMn",
                    "clcMdn",
                    "clcMde",
                    "clcSum",
                    "clcSD",
                    "clcVar",
                    "clcRng",
                    "clcMin",
                    "clcMax",
                    "clcIQR",
                    "drpNA"),
                rows=1,
                columns=list(
                    list(
                        `name`="fstCol", 
                        `title`=""))))}))

jtAggregateBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtAggregateBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtAggregate",
                version = c(1,0,0),
                options = options,
                results = jtAggregateResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Aggregate
#'
#' Aggregate Data (e.g., Calculate the Mean) From a Data Set in Long Format
#'
#' @examples
#' \donttest{
#' # the function is a wrapper for jmvReadWrite::aggregate_omv
#' # please use that function when in R (or in Rj)
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'}
#' @param data .
#' @param varAgg .
#' @param grpAgg .
#' @param clcN .
#' @param clcMss .
#' @param clcMn .
#' @param clcMdn .
#' @param clcMde .
#' @param clcSum .
#' @param clcSD .
#' @param clcVar .
#' @param clcRng .
#' @param clcMin .
#' @param clcMax .
#' @param clcIQR .
#' @param drpNA .
#' @param shwHlp .
#' @param jxfLog .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$fmtHTM} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$genInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dtaInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pvwDta} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pvwDta$asDF}
#'
#' \code{as.data.frame(results$pvwDta)}
#'
#' @export
jtAggregate <- function(
    data,
    varAgg,
    grpAgg,
    clcN = FALSE,
    clcMss = FALSE,
    clcMn = FALSE,
    clcMdn = FALSE,
    clcMde = FALSE,
    clcSum = FALSE,
    clcSD = FALSE,
    clcVar = FALSE,
    clcRng = FALSE,
    clcMin = FALSE,
    clcMax = FALSE,
    clcIQR = FALSE,
    drpNA = TRUE,
    shwHlp = FALSE,
    jxfLog = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtAggregate requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varAgg)) varAgg <- jmvcore::resolveQuo(jmvcore::enquo(varAgg))
    if ( ! missing(grpAgg)) grpAgg <- jmvcore::resolveQuo(jmvcore::enquo(grpAgg))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varAgg), varAgg, NULL),
            `if`( ! missing(grpAgg), grpAgg, NULL))


    options <- jtAggregateOptions$new(
        varAgg = varAgg,
        grpAgg = grpAgg,
        clcN = clcN,
        clcMss = clcMss,
        clcMn = clcMn,
        clcMdn = clcMdn,
        clcMde = clcMde,
        clcSum = clcSum,
        clcSD = clcSD,
        clcVar = clcVar,
        clcRng = clcRng,
        clcMin = clcMin,
        clcMax = clcMax,
        clcIQR = clcIQR,
        drpNA = drpNA,
        shwHlp = shwHlp,
        jxfLog = jxfLog)

    analysis <- jtAggregateClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

