
# This file is automatically generated, you probably don't want to edit this

jtArrangeColsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtArrangeColsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varOrd = NULL,
            fleOut = "Dataset_arrCol.omv",
            btnOut = NULL,
            blnOut = FALSE, ...) {

            super$initialize(
                package="jTransform",
                name="jtArrangeCols",
                requiresData=TRUE,
                ...)

            private$..varOrd <- jmvcore::OptionVariables$new(
                "varOrd",
                varOrd,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..fleOut <- jmvcore::OptionString$new(
                "fleOut",
                fleOut,
                default="Dataset_arrCol.omv")
            private$..btnOut <- jmvcore::OptionString$new(
                "btnOut",
                btnOut,
                hidden=TRUE)
            private$..blnOut <- jmvcore::OptionBool$new(
                "blnOut",
                blnOut,
                default=FALSE,
                hidden=TRUE)

            self$.addOption(private$..varOrd)
            self$.addOption(private$..fleOut)
            self$.addOption(private$..btnOut)
            self$.addOption(private$..blnOut)
        }),
    active = list(
        varOrd = function() private$..varOrd$value,
        fleOut = function() private$..fleOut$value,
        btnOut = function() private$..btnOut$value,
        blnOut = function() private$..blnOut$value),
    private = list(
        ..varOrd = NA,
        ..fleOut = NA,
        ..btnOut = NA,
        ..blnOut = NA)
)

jtArrangeColsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtArrangeColsResults",
    inherit = jmvcore::Group,
    active = list(
        txtInf = function() private$.items[["txtInf"]],
        txtOut = function() private$.items[["txtOut"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Change the order of variables")
            self$add(jmvcore::Html$new(
                options=options,
                name="txtInf",
                title="",
                refs="jmvReadWrite",
                content="<p><strong>This function re-arranges the order of columns in a jamovi data file.</strong></p> <p>Please assign the variables in their desired order to \u201CDesired order of variables\u201D. Please note that variables that you leave in the variable list to the left are not included in the output file.</p> <p>Under \u201COutput file\u201D, you can adjust the name of the output file. You may also add a directory to the file name. If no path is given, the output file is stored in the home directory.</p>\n"))
            self$add(jmvcore::Html$new(
                options=options,
                name="txtOut",
                title="",
                content=""))}))

jtArrangeColsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtArrangeColsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtArrangeCols",
                version = c(1,0,0),
                options = options,
                results = jtArrangeColsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Change the order of variables
#'
#' Change the order of variables
#'
#' @examples
#' # the function is a wrapper for jmvReadWrite::arrange_cols_omv
#' # please use that function when using R
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'
#' @param data .
#' @param varOrd .
#' @param fleOut .
#' @param btnOut .
#' @param blnOut .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$txtInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$txtOut} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
jtArrangeCols <- function(
    data,
    varOrd,
    fleOut = "Dataset_arrCol.omv",
    btnOut,
    blnOut = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtArrangeCols requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varOrd)) varOrd <- jmvcore::resolveQuo(jmvcore::enquo(varOrd))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varOrd), varOrd, NULL))


    options <- jtArrangeColsOptions$new(
        varOrd = varOrd,
        fleOut = fleOut,
        btnOut = btnOut,
        blnOut = blnOut)

    analysis <- jtArrangeColsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

