
# This file is automatically generated, you probably don't want to edit this

jtBatchConvertOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtBatchConvertOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            fleInp = "",
            tglChs = FALSE,
            fleChs = "",
            shwHlp = FALSE,
            btnCnv = FALSE,
            jxfLog = FALSE, ...) {

            super$initialize(
                package="jTransform",
                name="jtBatchConvert",
                requiresData=FALSE,
                ...)

            private$..fleInp <- jmvcore::OptionString$new(
                "fleInp",
                fleInp,
                default="")
            private$..tglChs <- jmvcore::OptionBool$new(
                "tglChs",
                tglChs,
                hidden=TRUE,
                default=FALSE)
            private$..fleChs <- jmvcore::OptionString$new(
                "fleChs",
                fleChs,
                hidden=TRUE,
                default="")
            private$..shwHlp <- jmvcore::OptionBool$new(
                "shwHlp",
                shwHlp,
                default=FALSE)
            private$..btnCnv <- jmvcore::OptionAction$new(
                "btnCnv",
                btnCnv,
                default=FALSE)
            private$..jxfLog <- jmvcore::OptionBool$new(
                "jxfLog",
                jxfLog,
                hidden=TRUE,
                default=FALSE)

            self$.addOption(private$..fleInp)
            self$.addOption(private$..tglChs)
            self$.addOption(private$..fleChs)
            self$.addOption(private$..shwHlp)
            self$.addOption(private$..btnCnv)
            self$.addOption(private$..jxfLog)
        }),
    active = list(
        fleInp = function() private$..fleInp$value,
        tglChs = function() private$..tglChs$value,
        fleChs = function() private$..fleChs$value,
        shwHlp = function() private$..shwHlp$value,
        btnCnv = function() private$..btnCnv$value,
        jxfLog = function() private$..jxfLog$value),
    private = list(
        ..fleInp = NA,
        ..tglChs = NA,
        ..fleChs = NA,
        ..shwHlp = NA,
        ..btnCnv = NA,
        ..jxfLog = NA)
)

jtBatchConvertResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtBatchConvertResults",
    inherit = jmvcore::Group,
    active = list(
        fmtHTM = function() private$.items[["fmtHTM"]],
        genInf = function() private$.items[["genInf"]],
        dtaInf = function() private$.items[["dtaInf"]],
        pvwDta = function() private$.items[["pvwDta"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Convert Multiple Data Files")
            self$add(jmvcore::Html$new(
                options=options,
                name="fmtHTM",
                clearWith=list(),
                content="<style> #fmtHTM { display: none; } table { width: 100%; border-collapse: collapse; } th { background-color: #3e6da9; color: white; text-align: left; } tbody > td { border: 1px solid #ddd; padding: 8px; } tbody > tr:nth-child(even) { background-color: #d6eaf8; } tbody > tr:nth-child(odd) { background-color: #ffffff; } tbody > tr:hover { background-color: #aed6f1; } </style>\n"))
            self$add(jmvcore::Html$new(
                options=options,
                name="genInf",
                visible="(shwHlp)",
                clearWith=list(),
                content="Either enter the name of (one or more) file(s) to be converted under \"Data Set(s) to Convert\" (separate mulitiple file names with semicolons), or use \"Browse...\" to select input file(s).</p>\n"))
            self$add(jmvcore::Html$new(
                options=options,
                name="dtaInf",
                clearWith=list(
                    "fleInp",
                    "btnCnv"),
                content=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="pvwDta",
                title="Data Preview",
                refs=list(
                    "jTransform",
                    "jmvReadWrite"),
                clearWith=list(
                    "fleInp"),
                rows=1,
                columns=list(
                    list(
                        `name`="fstCol", 
                        `title`=""))))}))

jtBatchConvertBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtBatchConvertBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtBatchConvert",
                version = c(1,0,0),
                options = options,
                results = jtBatchConvertResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Convert Multiple Data Files
#'
#' Convert Multiple Data Files
#'
#' @examples
#' \donttest{
#' # the function is a wrapper for jmvReadWrite::convert_omv
#' # please use that function when in R (or in Rj)
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'}
#' @param fleInp .
#' @param tglChs .
#' @param fleChs .
#' @param shwHlp .
#' @param btnCnv .
#' @param jxfLog .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$fmtHTM} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$genInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dtaInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pvwDta} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pvwDta$asDF}
#'
#' \code{as.data.frame(results$pvwDta)}
#'
#' @export
jtBatchConvert <- function(
    fleInp = "",
    tglChs = FALSE,
    fleChs = "",
    shwHlp = FALSE,
    btnCnv = FALSE,
    jxfLog = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtBatchConvert requires jmvcore to be installed (restart may be required)")


    options <- jtBatchConvertOptions$new(
        fleInp = fleInp,
        tglChs = tglChs,
        fleChs = fleChs,
        shwHlp = shwHlp,
        btnCnv = btnCnv,
        jxfLog = jxfLog)

    analysis <- jtBatchConvertClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

