
# This file is automatically generated, you probably don't want to edit this

jtCombineColsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtCombineColsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varAll = NULL,
            varPrs = NULL,
            mdeCmb = "none",
            shwHlp = FALSE,
            jxfLog = FALSE, ...) {

            super$initialize(
                package="jTransform",
                name="jtCombineCols",
                requiresData=TRUE,
                ...)

            private$..varAll <- jmvcore::OptionVariables$new(
                "varAll",
                varAll,
                hidden=TRUE,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                default=NULL)
            private$..varPrs <- jmvcore::OptionPairs$new(
                "varPrs",
                varPrs,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..mdeCmb <- jmvcore::OptionList$new(
                "mdeCmb",
                mdeCmb,
                options=list(
                    "none",
                    "first",
                    "second"),
                default="none")
            private$..shwHlp <- jmvcore::OptionBool$new(
                "shwHlp",
                shwHlp,
                default=FALSE)
            private$..btnCrt <- jmvcore::OptionAction$new(
                "btnCrt",
                FALSE,
                action="open")
            private$..jxfLog <- jmvcore::OptionBool$new(
                "jxfLog",
                jxfLog,
                hidden=TRUE,
                default=FALSE)

            self$.addOption(private$..varAll)
            self$.addOption(private$..varPrs)
            self$.addOption(private$..mdeCmb)
            self$.addOption(private$..shwHlp)
            self$.addOption(private$..btnCrt)
            self$.addOption(private$..jxfLog)
        }),
    active = list(
        varAll = function() private$..varAll$value,
        varPrs = function() private$..varPrs$value,
        mdeCmb = function() private$..mdeCmb$value,
        shwHlp = function() private$..shwHlp$value,
        btnCrt = function() private$..btnCrt$value,
        jxfLog = function() private$..jxfLog$value),
    private = list(
        ..varAll = NA,
        ..varPrs = NA,
        ..mdeCmb = NA,
        ..shwHlp = NA,
        ..btnCrt = NA,
        ..jxfLog = NA)
)

jtCombineColsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtCombineColsResults",
    inherit = jmvcore::Group,
    active = list(
        fmtHTM = function() private$.items[["fmtHTM"]],
        genInf = function() private$.items[["genInf"]],
        dtaInf = function() private$.items[["dtaInf"]],
        pvwDta = function() private$.items[["pvwDta"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Combine Columns")
            self$add(jmvcore::Html$new(
                options=options,
                name="fmtHTM",
                clearWith=list(),
                content="<style> #fmtHTM { display: none; } table { width: 100%; border-collapse: collapse; } th { background-color: #3e6da9; color: white; text-align: left; } tbody > td { border: 1px solid #ddd; padding: 8px; } tbody > tr:nth-child(even) { background-color: #d6eaf8; } tbody > tr:nth-child(odd) { background-color: #ffffff; } tbody > tr:hover { background-color: #aed6f1; } </style>\n"))
            self$add(jmvcore::Html$new(
                options=options,
                name="genInf",
                visible="(shwHlp)",
                clearWith=list(),
                content="Please assign the pairs of variables to be combined to \"Variable Pairs to Combine\". The two variables in a pair are combined into the first variable whereas the second variable is removed from the data set. \"Mode of Combining\" determines what the function does if the values in the variable pair are not in accordance (i.e., if they are unequal). \"\" throws an error and stops, \"First Variable takes Precedence\" means that the values from the first variable of each pair are taken if the values do not match up, when \"Second Variable takes Precedence\" is set, the values of the second variable are taken in such cases.\n"))
            self$add(jmvcore::Html$new(
                options=options,
                name="dtaInf",
                clearWith=list(
                    "varPrs",
                    "mdeCmb",
                    "btnCrt"),
                content=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="pvwDta",
                title="Data Preview",
                refs=list(
                    "jTransform",
                    "jmvReadWrite"),
                clearWith=list(
                    "varPrs",
                    "mdeCmb"),
                rows=1,
                columns=list(
                    list(
                        `name`="fstCol", 
                        `title`=""))))}))

jtCombineColsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtCombineColsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtCombineCols",
                version = c(1,0,0),
                options = options,
                results = jtCombineColsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Combine Columns
#'
#' Combine Pairs of Variables Into One Variable
#'
#' @examples
#' \donttest{
#' # the function is a wrapper for jmvReadWrite::combine_cols_omv
#' # please use that function when in R (or in Rj)
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'}
#' @param data .
#' @param varAll .
#' @param varPrs .
#' @param mdeCmb .
#' @param shwHlp .
#' @param btnCrt .
#' @param jxfLog .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$fmtHTM} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$genInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dtaInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pvwDta} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pvwDta$asDF}
#'
#' \code{as.data.frame(results$pvwDta)}
#'
#' @export
jtCombineCols <- function(
    data,
    varAll = NULL,
    varPrs,
    mdeCmb = "none",
    shwHlp = FALSE,
    jxfLog = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtCombineCols requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varAll)) varAll <- jmvcore::resolveQuo(jmvcore::enquo(varAll))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varAll), varAll, NULL))


    options <- jtCombineColsOptions$new(
        varAll = varAll,
        varPrs = varPrs,
        mdeCmb = mdeCmb,
        shwHlp = shwHlp,
        jxfLog = jxfLog)

    analysis <- jtCombineColsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

