
# This file is automatically generated, you probably don't want to edit this

jtDistancesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtDistancesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varDst = NULL,
            clmDst = "columns",
            stdDst = "none",
            nmeDst = "euclid",
            pwrDst = 2,
            rt_Dst = 2,
            p__Dst = "1",
            np_Dst = "0",
            shwHlp = FALSE,
            jxfLog = FALSE, ...) {

            super$initialize(
                package="jTransform",
                name="jtDistances",
                requiresData=TRUE,
                ...)

            private$..varDst <- jmvcore::OptionVariables$new(
                "varDst",
                varDst,
                permitted=list(
                    "numeric",
                    "factor"),
                required=TRUE,
                default=NULL)
            private$..clmDst <- jmvcore::OptionList$new(
                "clmDst",
                clmDst,
                options=list(
                    "columns",
                    "rows"),
                default="columns")
            private$..stdDst <- jmvcore::OptionList$new(
                "stdDst",
                stdDst,
                options=list(
                    "none",
                    "z",
                    "sd",
                    "range",
                    "max",
                    "mean",
                    "rescale"),
                default="none")
            private$..nmeDst <- jmvcore::OptionList$new(
                "nmeDst",
                nmeDst,
                options=list(
                    "euclid",
                    "seuclid",
                    "block",
                    "canberra",
                    "chebychev",
                    "minkowski",
                    "power",
                    "cosine",
                    "correlation",
                    "chisq",
                    "ph2",
                    "rr",
                    "sm",
                    "jaccards",
                    "jaccardd",
                    "dice",
                    "rt",
                    "k1",
                    "ss1",
                    "ss2",
                    "ss3",
                    "k2",
                    "ss4",
                    "hamann",
                    "lambda",
                    "d",
                    "y",
                    "q",
                    "ochiai",
                    "ss5",
                    "phi",
                    "beuclid",
                    "bseuclid",
                    "size",
                    "pattern",
                    "bshape",
                    "disper",
                    "variance",
                    "blwmn",
                    "none"),
                default="euclid")
            private$..pwrDst <- jmvcore::OptionInteger$new(
                "pwrDst",
                pwrDst,
                default=2)
            private$..rt_Dst <- jmvcore::OptionInteger$new(
                "rt_Dst",
                rt_Dst,
                default=2)
            private$..p__Dst <- jmvcore::OptionString$new(
                "p__Dst",
                p__Dst,
                default="1")
            private$..np_Dst <- jmvcore::OptionString$new(
                "np_Dst",
                np_Dst,
                default="0")
            private$..shwHlp <- jmvcore::OptionBool$new(
                "shwHlp",
                shwHlp,
                default=FALSE)
            private$..btnCrt <- jmvcore::OptionAction$new(
                "btnCrt",
                FALSE,
                action="open")
            private$..jxfLog <- jmvcore::OptionBool$new(
                "jxfLog",
                jxfLog,
                hidden=TRUE,
                default=FALSE)

            self$.addOption(private$..varDst)
            self$.addOption(private$..clmDst)
            self$.addOption(private$..stdDst)
            self$.addOption(private$..nmeDst)
            self$.addOption(private$..pwrDst)
            self$.addOption(private$..rt_Dst)
            self$.addOption(private$..p__Dst)
            self$.addOption(private$..np_Dst)
            self$.addOption(private$..shwHlp)
            self$.addOption(private$..btnCrt)
            self$.addOption(private$..jxfLog)
        }),
    active = list(
        varDst = function() private$..varDst$value,
        clmDst = function() private$..clmDst$value,
        stdDst = function() private$..stdDst$value,
        nmeDst = function() private$..nmeDst$value,
        pwrDst = function() private$..pwrDst$value,
        rt_Dst = function() private$..rt_Dst$value,
        p__Dst = function() private$..p__Dst$value,
        np_Dst = function() private$..np_Dst$value,
        shwHlp = function() private$..shwHlp$value,
        btnCrt = function() private$..btnCrt$value,
        jxfLog = function() private$..jxfLog$value),
    private = list(
        ..varDst = NA,
        ..clmDst = NA,
        ..stdDst = NA,
        ..nmeDst = NA,
        ..pwrDst = NA,
        ..rt_Dst = NA,
        ..p__Dst = NA,
        ..np_Dst = NA,
        ..shwHlp = NA,
        ..btnCrt = NA,
        ..jxfLog = NA)
)

jtDistancesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtDistancesResults",
    inherit = jmvcore::Group,
    active = list(
        fmtHTM = function() private$.items[["fmtHTM"]],
        genInf = function() private$.items[["genInf"]],
        dtaInf = function() private$.items[["dtaInf"]],
        pvwDta = function() private$.items[["pvwDta"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Calculate Distances")
            self$add(jmvcore::Html$new(
                options=options,
                name="fmtHTM",
                clearWith=list(),
                content="<style> #fmtHTM { display: none; } table { width: 100%; border-collapse: collapse; } th { background-color: #3e6da9; color: white; text-align: left; } tbody > td { border: 1px solid #ddd; padding: 8px; } tbody > tr:nth-child(even) { background-color: #d6eaf8; } tbody > tr:nth-child(odd) { background-color: #ffffff; } tbody > tr:hover { background-color: #aed6f1; } </style>\n"))
            self$add(jmvcore::Html$new(
                options=options,
                name="genInf",
                visible="(shwHlp)",
                clearWith=list(),
                content="Please assign the variables from the data set that should be included in the calculation of distances to \"Variables To Calculate Distances For\" and then select whether the distances are to be calculated between \"Columns\" or \"Rows\". You need at least two variables and two rows to calculate distances. Select then whether the input data are to be standardized (before calculating the distances) and which distance measure should be calculated.\n"))
            self$add(jmvcore::Html$new(
                options=options,
                name="dtaInf",
                clearWith=list(
                    "varDst",
                    "clmDst",
                    "btnCrt"),
                content=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="pvwDta",
                title="Data Preview",
                refs=list(
                    "jTransform",
                    "jmvReadWrite"),
                clearWith=list(
                    "varDst",
                    "clmDst",
                    "stdDst",
                    "nmeDst"),
                rows=1,
                columns=list(
                    list(
                        `name`="fstCol", 
                        `title`=""))))}))

jtDistancesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtDistancesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtDistances",
                version = c(1,0,0),
                options = options,
                results = jtDistancesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Calculate Distances
#'
#' 
#' @param data .
#' @param varDst .
#' @param clmDst .
#' @param stdDst .
#' @param nmeDst .
#' @param pwrDst .
#' @param rt_Dst .
#' @param p__Dst .
#' @param np_Dst .
#' @param shwHlp .
#' @param btnCrt .
#' @param jxfLog .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$fmtHTM} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$genInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dtaInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pvwDta} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pvwDta$asDF}
#'
#' \code{as.data.frame(results$pvwDta)}
#'
#' @export
jtDistances <- function(
    data,
    varDst = NULL,
    clmDst = "columns",
    stdDst = "none",
    nmeDst = "euclid",
    pwrDst = 2,
    rt_Dst = 2,
    p__Dst = "1",
    np_Dst = "0",
    shwHlp = FALSE,
    jxfLog = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtDistances requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varDst)) varDst <- jmvcore::resolveQuo(jmvcore::enquo(varDst))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varDst), varDst, NULL))


    options <- jtDistancesOptions$new(
        varDst = varDst,
        clmDst = clmDst,
        stdDst = stdDst,
        nmeDst = nmeDst,
        pwrDst = pwrDst,
        rt_Dst = rt_Dst,
        p__Dst = p__Dst,
        np_Dst = np_Dst,
        shwHlp = shwHlp,
        jxfLog = jxfLog)

    analysis <- jtDistancesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

