
# This file is automatically generated, you probably don't want to edit this

jtlong2wideOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtlong2wideOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rowstocols = NULL,
            covs = NULL,
            index = NULL,
            id = NULL,
            btnOut = NULL, ...) {

            super$initialize(
                package="jTransform",
                name="jtlong2wide",
                requiresData=TRUE,
                ...)

            private$..rowstocols <- jmvcore::OptionVariables$new(
                "rowstocols",
                rowstocols)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs)
            private$..index <- jmvcore::OptionVariables$new(
                "index",
                index)
            private$..id <- jmvcore::OptionVariable$new(
                "id",
                id)
            private$..btnOut <- jmvcore::OptionAction$new(
                "btnOut",
                btnOut)

            self$.addOption(private$..rowstocols)
            self$.addOption(private$..covs)
            self$.addOption(private$..index)
            self$.addOption(private$..id)
            self$.addOption(private$..btnOut)
        }),
    active = list(
        rowstocols = function() private$..rowstocols$value,
        covs = function() private$..covs$value,
        index = function() private$..index$value,
        id = function() private$..id$value,
        btnOut = function() private$..btnOut$value),
    private = list(
        ..rowstocols = NA,
        ..covs = NA,
        ..index = NA,
        ..id = NA,
        ..btnOut = NA)
)

jtlong2wideResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtlong2wideResults",
    inherit = jmvcore::Group,
    active = list(
        help = function() private$.items[["help"]],
        info = function() private$.items[["info"]],
        features = function() private$.items[["features"]],
        showdata = function() private$.items[["showdata"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Long to wide")
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                title="Getting started"))
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Info Table",
                clearWith=list(
                    "rowstocols",
                    "index",
                    "id",
                    "covs"),
                columns=list(
                    list(
                        `name`="text", 
                        `title`="Info", 
                        `type`="text"),
                    list(
                        `name`="var", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="features",
                title="New created variables",
                clearWith=list(
                    "rowstocols",
                    "index",
                    "id",
                    "covs"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="New Variables", 
                        `type`="text"),
                    list(
                        `name`="lab", 
                        `title`="Original Levels", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="showdata",
                title="Data Preview",
                clearWith=list(
                    "rowstocols",
                    "index",
                    "id",
                    "covs"),
                columns=list(
                    list(
                        `name`="row", 
                        `title`="Rows", 
                        `type`="integer"))))}))

jtlong2wideBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtlong2wideBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtlong2wide",
                version = c(1,0,0),
                options = options,
                results = jtlong2wideResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Long to wide
#'
#' 
#' @param data .
#' @param rowstocols .
#' @param covs .
#' @param index .
#' @param id .
#' @param btnOut .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$features} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$showdata} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
jtlong2wide <- function(
    data,
    rowstocols,
    covs,
    index,
    id,
    btnOut) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtlong2wide requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rowstocols)) rowstocols <- jmvcore::resolveQuo(jmvcore::enquo(rowstocols))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(index)) index <- jmvcore::resolveQuo(jmvcore::enquo(index))
    if ( ! missing(id)) id <- jmvcore::resolveQuo(jmvcore::enquo(id))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rowstocols), rowstocols, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(index), index, NULL),
            `if`( ! missing(id), id, NULL))


    options <- jtlong2wideOptions$new(
        rowstocols = rowstocols,
        covs = covs,
        index = index,
        id = id,
        btnOut = btnOut)

    analysis <- jtlong2wideClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

