
# This file is automatically generated, you probably don't want to edit this

jtMergeColsOptions <- if (requireNamespace("jmvcore", quietly = TRUE)) R6::R6Class(
    "jtMergeColsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varBy = NULL,
            varAll = NULL,
            fleInp = "",
            tglChs = FALSE,
            fleChs = "",
            typMrg = "outer",
            shwHlp = FALSE,
            btnCrt = FALSE,
            jxfLog = FALSE, ...) {

            super$initialize(
                package = "jTransform",
                name = "jtMergeCols",
                requiresData = TRUE,
                ...)

            private$..varBy <- jmvcore::OptionVariables$new(
                "varBy",
                varBy,
                permitted = list(
                    "numeric",
                    "factor",
                    "id"),
                default = NULL)
            private$..varAll <- jmvcore::OptionVariables$new(
                "varAll",
                varAll,
                hidden = TRUE,
                permitted = list(
                    "numeric",
                    "factor",
                    "id"),
                default = NULL)
            private$..fleInp <- jmvcore::OptionString$new(
                "fleInp",
                fleInp,
                default = "")
            private$..tglChs <- jmvcore::OptionBool$new(
                "tglChs",
                tglChs,
                hidden = TRUE,
                default = FALSE)
            private$..fleChs <- jmvcore::OptionString$new(
                "fleChs",
                fleChs,
                hidden = TRUE,
                default = "")
            private$..typMrg <- jmvcore::OptionList$new(
                "typMrg",
                typMrg,
                options = list(
                    "outer",
                    "inner",
                    "left",
                    "right"),
                default = "outer")
            private$..shwHlp <- jmvcore::OptionBool$new(
                "shwHlp",
                shwHlp,
                default = FALSE)
            private$..btnCrt <- jmvcore::OptionAction$new(
                "btnCrt",
                btnCrt,
                default = FALSE)
            private$..jxfLog <- jmvcore::OptionBool$new(
                "jxfLog",
                jxfLog,
                hidden = TRUE,
                default = FALSE)

            self$.addOption(private$..varBy)
            self$.addOption(private$..varAll)
            self$.addOption(private$..fleInp)
            self$.addOption(private$..tglChs)
            self$.addOption(private$..fleChs)
            self$.addOption(private$..typMrg)
            self$.addOption(private$..shwHlp)
            self$.addOption(private$..btnCrt)
            self$.addOption(private$..jxfLog)
        }),
    active = list(
        varBy = function() private$..varBy$value,
        varAll = function() private$..varAll$value,
        fleInp = function() private$..fleInp$value,
        tglChs = function() private$..tglChs$value,
        fleChs = function() private$..fleChs$value,
        typMrg = function() private$..typMrg$value,
        shwHlp = function() private$..shwHlp$value,
        btnCrt = function() private$..btnCrt$value,
        jxfLog = function() private$..jxfLog$value),
    private = list(
        ..varBy = NA,
        ..varAll = NA,
        ..fleInp = NA,
        ..tglChs = NA,
        ..fleChs = NA,
        ..typMrg = NA,
        ..shwHlp = NA,
        ..btnCrt = NA,
        ..jxfLog = NA)
)

jtMergeColsResults <- if (requireNamespace("jmvcore", quietly = TRUE)) R6::R6Class(
    "jtMergeColsResults",
    inherit = jmvcore::Group,
    active = list(
        fmtHTM = function() private$.items[["fmtHTM"]],
        genInf = function() private$.items[["genInf"]],
        dtaInf = function() private$.items[["dtaInf"]],
        pvwDta = function() private$.items[["pvwDta"]],
        addInf = function() private$.items[["addInf"]]),
    private = list(),
    public = list(
        initialize = function(options) {
            super$initialize(
                options = options,
                name = "",
                title = "Merge (Add Columns)")
            self$add(jmvcore::Html$new(
                options = options,
                name = "fmtHTM",
                clearWith = list(),
                content = "<style> #fmtHTM { display: none; } table { width: 100%; border-collapse: collapse; } th { background-color: #3e6da9; color: white; text-align: left; } tbody > td { border: 1px solid #ddd; padding: 8px; } tbody > tr:nth-child(even) { background-color: #d6eaf8; } tbody > tr:nth-child(odd) { background-color: #ffffff; } tbody > tr:hover { background-color: #aed6f1; } </style>\n"))
            self$add(jmvcore::Html$new(
                options = options,
                name = "genInf",
                visible = "(shwHlp)",
                clearWith = list(),
                content = "Please assign one or more variables that appear in all data sets (e.g., a participant code) to \"Variable(s) to Match the Data Sets by\". Afterwards, either write the name of (one or more) file(s) to be merged under \"Data Set(s) to Add\" (separate mulitiple file names with semicolons), or use \"Browse...\" to select input file(s).</p> <p>For a more comprehensive explanation regarding the types of merging operations, see \"Details\" underneath the preview table.\n"))
            self$add(jmvcore::Html$new(
                options = options,
                name = "dtaInf",
                clearWith = list(
                    "varBy",
                    "varAll",
                    "fleInp",
                    "typMrg",
                    "btnCrt"),
                content = ""))
            self$add(jmvcore::Table$new(
                options = options,
                name = "pvwDta",
                title = "Data Preview",
                refs = list(
                    "jTransform",
                    "jmvReadWrite"),
                clearWith = list(
                    "varBy",
                    "varAll",
                    "fleInp",
                    "typMrg"),
                rows = 1,
                columns = list(
                    list(
                        `name` = "fstCol", 
                        `title` = ""))))
            self$add(jmvcore::Html$new(
                options = options,
                name = "addInf",
                visible = "(shwHlp)",
                clearWith = list(),
                content = "<h2>Details</h2> <p>There are four different types of merging operations: The option \"Keeps All Cases (Rows)\" keeps all cases (but if some input data sets did not contain that value of the matching variable, there might be missing values for variable from that data set). The second option \"Keeps Only Cases Contained in All Merged Data Sets\" keeps only those cases where a particular value of the matching variable was contained in all datasets. The option \"Keeps All Cases From the Currently Opened Data Set\" keeps all rows / cases from the active data set (whereas cases that are only contained in the data sets defined under \"Data Set(s) to Add\" are dropped). The option \"Keeps All Cases From the Data Sets To Be Added\" keeps all cases from the data sets defined under \"Data Set(s) to Add\" (whereas cases that are only contained in the active data set are dropped).</p> <p>If there are variables with the same name in several of the input data sets, it will checked whether they contain the same content. If they are the same, only the first of these identical variables is kept (and the others are removed). If they are different, the name of the first of these variables is kept, and a suffix with their position (_2, _3, etc.) will be added to the name of all other variables.</p>\n"))}))

jtMergeColsBase <- if (requireNamespace("jmvcore", quietly = TRUE)) R6::R6Class(
    "jtMergeColsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data = NULL, datasetId = "", analysisId = "", revision = 0) {
            super$initialize(
                package = "jTransform",
                name = "jtMergeCols",
                version = c(1,0,0),
                options = options,
                results = jtMergeColsResults$new(options = options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Merge (Add Columns)
#'
#' Add Columns (From Other Data Sets)
#'
#' @examples
#' \donttest{
#' # the function is a wrapper for jmvReadWrite::merge_cols_omv
#' # please use that function when in R (or in Rj)
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'}
#' @param data the data as a data frame
#' @param varBy .
#' @param varAll .
#' @param fleInp .
#' @param tglChs .
#' @param fleChs .
#' @param typMrg .
#' @param shwHlp .
#' @param btnCrt .
#' @param jxfLog .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$fmtHTM} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$genInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dtaInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pvwDta} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$addInf} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pvwDta$asDF}
#'
#' \code{as.data.frame(results$pvwDta)}
#'
#' @export
jtMergeCols <- function(
    data,
    varBy = NULL,
    varAll = NULL,
    fleInp = "",
    tglChs = FALSE,
    fleChs = "",
    typMrg = "outer",
    shwHlp = FALSE,
    btnCrt = FALSE,
    jxfLog = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly = TRUE))
        stop("jtMergeCols requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varBy)) varBy <- jmvcore::resolveQuo(jmvcore::enquo(varBy))
    if ( ! missing(varAll)) varAll <- jmvcore::resolveQuo(jmvcore::enquo(varAll))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varBy), varBy, NULL),
            `if`( ! missing(varAll), varAll, NULL))


    options <- jtMergeColsOptions$new(
        varBy = varBy,
        varAll = varAll,
        fleInp = fleInp,
        tglChs = tglChs,
        fleChs = fleChs,
        typMrg = typMrg,
        shwHlp = shwHlp,
        btnCrt = btnCrt,
        jxfLog = jxfLog)

    analysis <- jtMergeColsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

