
# This file is automatically generated, you probably don't want to edit this

jtmergeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtmergeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varBy = NULL,
            varAll = NULL,
            fleInp = "",
            fleChs = NULL,
            type = "outer",
            common = "both",
            btnOpenFile = NULL,
            btnOut = NULL, ...) {

            super$initialize(
                package="jTransform",
                name="jtmerge",
                requiresData=TRUE,
                ...)

            private$..varBy <- jmvcore::OptionVariables$new(
                "varBy",
                varBy,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..varAll <- jmvcore::OptionVariables$new(
                "varAll",
                varAll,
                hidden=TRUE,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..fleInp <- jmvcore::OptionString$new(
                "fleInp",
                fleInp,
                default="")
            private$..fleChs <- jmvcore::OptionString$new(
                "fleChs",
                fleChs,
                hidden=TRUE)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "outer",
                    "inner",
                    "left",
                    "right"),
                default="outer")
            private$..common <- jmvcore::OptionList$new(
                "common",
                common,
                options=list(
                    "both",
                    "left",
                    "right"),
                default="both")
            private$..btnOpenFile <- jmvcore::OptionAction$new(
                "btnOpenFile",
                btnOpenFile)
            private$..btnOut <- jmvcore::OptionAction$new(
                "btnOut",
                btnOut)

            self$.addOption(private$..varBy)
            self$.addOption(private$..varAll)
            self$.addOption(private$..fleInp)
            self$.addOption(private$..fleChs)
            self$.addOption(private$..type)
            self$.addOption(private$..common)
            self$.addOption(private$..btnOpenFile)
            self$.addOption(private$..btnOut)
        }),
    active = list(
        varBy = function() private$..varBy$value,
        varAll = function() private$..varAll$value,
        fleInp = function() private$..fleInp$value,
        fleChs = function() private$..fleChs$value,
        type = function() private$..type$value,
        common = function() private$..common$value,
        btnOpenFile = function() private$..btnOpenFile$value,
        btnOut = function() private$..btnOut$value),
    private = list(
        ..varBy = NA,
        ..varAll = NA,
        ..fleInp = NA,
        ..fleChs = NA,
        ..type = NA,
        ..common = NA,
        ..btnOpenFile = NA,
        ..btnOut = NA)
)

jtmergeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtmergeResults",
    inherit = jmvcore::Group,
    active = list(
        help = function() private$.items[["help"]],
        desc = function() private$.items[["desc"]],
        info = function() private$.items[["info"]],
        features = function() private$.items[["features"]],
        showdata = function() private$.items[["showdata"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Merge Datasets (add columns)")
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                title="Getting started",
                clearWith=list(
                    "fleInp",
                    "varBy",
                    "btnOut")))
            self$add(jmvcore::Html$new(
                options=options,
                name="desc",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Info Table",
                clearWith=list(
                    "fleInp",
                    "varBy",
                    "common",
                    "type",
                    "common"),
                columns=list(
                    list(
                        `name`="text", 
                        `title`="Info", 
                        `type`="text"),
                    list(
                        `name`="var", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="features",
                title="Common Variables",
                clearWith=list(
                    "fleInp",
                    "varBy"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="lab1", 
                        `title`="Type.x", 
                        `type`="text"),
                    list(
                        `name`="lab2", 
                        `title`="Type.y", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="showdata",
                title="Data Preview",
                clearWith=list(
                    "fleInp",
                    "varBy",
                    "type",
                    "common"),
                columns=list(
                    list(
                        `name`="row", 
                        `title`="Rows", 
                        `type`="integer"))))}))

jtmergeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtmergeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtmerge",
                version = c(1,0,0),
                options = options,
                results = jtmergeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Merge Datasets (add columns)
#'
#' Add columns (from other data sets)
#'
#' @examples
#' \dontrun{
#' # the function is a wrapper for jmvReadWrite::merge_cols_omv
#' # please use that function when in R (or in Rj)
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'}
#' @param data the data as a data frame
#' @param varBy .
#' @param varAll .
#' @param fleInp .
#' @param fleChs .
#' @param type .
#' @param common .
#' @param btnOpenFile .
#' @param btnOut .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$features} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$showdata} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
jtmerge <- function(
    data,
    varBy,
    varAll,
    fleInp = "",
    fleChs,
    type = "outer",
    common = "both",
    btnOpenFile,
    btnOut) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtmerge requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varBy)) varBy <- jmvcore::resolveQuo(jmvcore::enquo(varBy))
    if ( ! missing(varAll)) varAll <- jmvcore::resolveQuo(jmvcore::enquo(varAll))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varBy), varBy, NULL),
            `if`( ! missing(varAll), varAll, NULL))


    options <- jtmergeOptions$new(
        varBy = varBy,
        varAll = varAll,
        fleInp = fleInp,
        fleChs = fleChs,
        type = type,
        common = common,
        btnOpenFile = btnOpenFile,
        btnOut = btnOut)

    analysis <- jtmergeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

