
# This file is automatically generated, you probably don't want to edit this

jtreorderOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtreorderOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varAll = NULL,
            varOrd = NULL,
            add = "all",
            btnOut = NULL, ...) {

            super$initialize(
                package="jTransform",
                name="jtreorder",
                requiresData=TRUE,
                ...)

            private$..varAll <- jmvcore::OptionVariables$new(
                "varAll",
                varAll,
                hidden=TRUE,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..varOrd <- jmvcore::OptionVariables$new(
                "varOrd",
                varOrd,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..add <- jmvcore::OptionList$new(
                "add",
                add,
                options=list(
                    "all",
                    "sel"),
                default="all")
            private$..btnOut <- jmvcore::OptionAction$new(
                "btnOut",
                btnOut)

            self$.addOption(private$..varAll)
            self$.addOption(private$..varOrd)
            self$.addOption(private$..add)
            self$.addOption(private$..btnOut)
        }),
    active = list(
        varAll = function() private$..varAll$value,
        varOrd = function() private$..varOrd$value,
        add = function() private$..add$value,
        btnOut = function() private$..btnOut$value),
    private = list(
        ..varAll = NA,
        ..varOrd = NA,
        ..add = NA,
        ..btnOut = NA)
)

jtreorderResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtreorderResults",
    inherit = jmvcore::Group,
    active = list(
        help = function() private$.items[["help"]],
        desc = function() private$.items[["desc"]],
        info = function() private$.items[["info"]],
        showdata = function() private$.items[["showdata"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Re-order variables")
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                visible=TRUE,
                clearWith=list(
                    "varOrd",
                    "btnOut",
                    "add")))
            self$add(jmvcore::Html$new(
                options=options,
                name="desc",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Info Table",
                refs=list(
                    "jTransform",
                    "jmvReadWrite"),
                clearWith=list(
                    "varOrd",
                    "add"),
                columns=list(
                    list(
                        `name`="text", 
                        `title`="Info", 
                        `type`="text"),
                    list(
                        `name`="var", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="showdata",
                title="Data Preview",
                clearWith=list(
                    "varOrd",
                    "add"),
                columns=list(
                    list(
                        `name`="row", 
                        `title`="Rows", 
                        `type`="integer"))))}))

jtreorderBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtreorderBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtreorder",
                version = c(1,0,0),
                options = options,
                results = jtreorderResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Re-order variables
#'
#' Change the order of variables
#'
#' @examples
#' \dontrun{
#' # the function is a wrapper for jmvReadWrite::arrange_cols_omv
#' # please use that function when in R (or in Rj)
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'}
#' @param data .
#' @param varAll .
#' @param varOrd .
#' @param add .
#' @param btnOut .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$showdata} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
jtreorder <- function(
    data,
    varAll,
    varOrd,
    add = "all",
    btnOut) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtreorder requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varAll)) varAll <- jmvcore::resolveQuo(jmvcore::enquo(varAll))
    if ( ! missing(varOrd)) varOrd <- jmvcore::resolveQuo(jmvcore::enquo(varOrd))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varAll), varAll, NULL),
            `if`( ! missing(varOrd), varOrd, NULL))


    options <- jtreorderOptions$new(
        varAll = varAll,
        varOrd = varOrd,
        add = add,
        btnOut = btnOut)

    analysis <- jtreorderClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

