
# This file is automatically generated, you probably don't want to edit this

jtReplaceOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtReplaceOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varAll = NULL,
            rplCst = "",
            rplTrm = "",
            whlTrm = TRUE,
            btnOut = NULL,
            incCmp = TRUE,
            incRcd = TRUE,
            incID = TRUE,
            incNom = TRUE,
            incOrd = TRUE,
            incNum = TRUE,
            incExc = "include",
            varSel = NULL, ...) {

            super$initialize(
                package="jTransform",
                name="jtReplace",
                requiresData=TRUE,
                ...)

            private$..varAll <- jmvcore::OptionVariables$new(
                "varAll",
                varAll,
                hidden=TRUE,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..rplCst <- jmvcore::OptionString$new(
                "rplCst",
                rplCst,
                default="",
                hidden=TRUE)
            private$..rplTrm <- jmvcore::OptionString$new(
                "rplTrm",
                rplTrm,
                default="",
                hidden=TRUE)
            private$..whlTrm <- jmvcore::OptionBool$new(
                "whlTrm",
                whlTrm,
                default=TRUE)
            private$..btnOut <- jmvcore::OptionAction$new(
                "btnOut",
                btnOut)
            private$..incCmp <- jmvcore::OptionBool$new(
                "incCmp",
                incCmp,
                default=TRUE)
            private$..incRcd <- jmvcore::OptionBool$new(
                "incRcd",
                incRcd,
                default=TRUE)
            private$..incID <- jmvcore::OptionBool$new(
                "incID",
                incID,
                default=TRUE)
            private$..incNom <- jmvcore::OptionBool$new(
                "incNom",
                incNom,
                default=TRUE)
            private$..incOrd <- jmvcore::OptionBool$new(
                "incOrd",
                incOrd,
                default=TRUE)
            private$..incNum <- jmvcore::OptionBool$new(
                "incNum",
                incNum,
                default=TRUE)
            private$..incExc <- jmvcore::OptionList$new(
                "incExc",
                incExc,
                options=list(
                    "include",
                    "exclude"),
                default="include")
            private$..varSel <- jmvcore::OptionVariables$new(
                "varSel",
                varSel,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))

            self$.addOption(private$..varAll)
            self$.addOption(private$..rplCst)
            self$.addOption(private$..rplTrm)
            self$.addOption(private$..whlTrm)
            self$.addOption(private$..btnOut)
            self$.addOption(private$..incCmp)
            self$.addOption(private$..incRcd)
            self$.addOption(private$..incID)
            self$.addOption(private$..incNom)
            self$.addOption(private$..incOrd)
            self$.addOption(private$..incNum)
            self$.addOption(private$..incExc)
            self$.addOption(private$..varSel)
        }),
    active = list(
        varAll = function() private$..varAll$value,
        rplCst = function() private$..rplCst$value,
        rplTrm = function() private$..rplTrm$value,
        whlTrm = function() private$..whlTrm$value,
        btnOut = function() private$..btnOut$value,
        incCmp = function() private$..incCmp$value,
        incRcd = function() private$..incRcd$value,
        incID = function() private$..incID$value,
        incNom = function() private$..incNom$value,
        incOrd = function() private$..incOrd$value,
        incNum = function() private$..incNum$value,
        incExc = function() private$..incExc$value,
        varSel = function() private$..varSel$value),
    private = list(
        ..varAll = NA,
        ..rplCst = NA,
        ..rplTrm = NA,
        ..whlTrm = NA,
        ..btnOut = NA,
        ..incCmp = NA,
        ..incRcd = NA,
        ..incID = NA,
        ..incNom = NA,
        ..incOrd = NA,
        ..incNum = NA,
        ..incExc = NA,
        ..varSel = NA)
)

jtReplaceResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtReplaceResults",
    inherit = jmvcore::Group,
    active = list(
        txtPvw = function() private$.items[["txtPvw"]],
        txtInf = function() private$.items[["txtInf"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Replace values in the current data set")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="txtPvw",
                title="Output Preview",
                clearWith=list()))
            self$add(jmvcore::Html$new(
                options=options,
                name="txtInf",
                refs=list(
                    "jTransform",
                    "jmvReadWrite"),
                clearWith=list(),
                content="<h2>Details</h2> <p><strong>This function replaces values in a jamovi data set.</strong> </p> <p>Please type the original value and the replacement into the text box. Original and replacement should be separated by a comma. If you want to have several pairs of original and to replacment values, use separate lines. If you want to replace partial matches, unset the tick box \u201Cwhole word\u201D (e.g., for orginal: 24 and replacement: 34, 241 will be changed into 341).</p> <p>The \u201CInclude / exclude\u201D collapse box permits to specifically select in which column types, for which measurement type, and in which variables the search shall be conducted.</p>\n"))}))

jtReplaceBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtReplaceBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtReplace",
                version = c(1,0,0),
                options = options,
                results = jtReplaceResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Replace values in the current data set
#'
#' Replace values in the current data set
#'
#' @examples
#' \dontrun{
#' # the function is a wrapper for jmvReadWrite::replace_omv
#' # please use that function when in R (or in Rj)
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'}
#' @param data .
#' @param varAll .
#' @param rplCst .
#' @param rplTrm .
#' @param whlTrm .
#' @param btnOut .
#' @param incCmp .
#' @param incRcd .
#' @param incID .
#' @param incNom .
#' @param incOrd .
#' @param incNum .
#' @param incExc .
#' @param varSel .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$txtPvw} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$txtInf} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
jtReplace <- function(
    data,
    varAll,
    rplCst = "",
    rplTrm = "",
    whlTrm = TRUE,
    btnOut,
    incCmp = TRUE,
    incRcd = TRUE,
    incID = TRUE,
    incNom = TRUE,
    incOrd = TRUE,
    incNum = TRUE,
    incExc = "include",
    varSel) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtReplace requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varAll)) varAll <- jmvcore::resolveQuo(jmvcore::enquo(varAll))
    if ( ! missing(varSel)) varSel <- jmvcore::resolveQuo(jmvcore::enquo(varSel))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varAll), varAll, NULL),
            `if`( ! missing(varSel), varSel, NULL))


    options <- jtReplaceOptions$new(
        varAll = varAll,
        rplCst = rplCst,
        rplTrm = rplTrm,
        whlTrm = whlTrm,
        btnOut = btnOut,
        incCmp = incCmp,
        incRcd = incRcd,
        incID = incID,
        incNom = incNom,
        incOrd = incOrd,
        incNum = incNum,
        incExc = incExc,
        varSel = varSel)

    analysis <- jtReplaceClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

