
# This file is automatically generated, you probably don't want to edit this

jtReplaceOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtReplaceOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varAll = NULL,
            rplTrm = list(
                list(rplOld="", rplNew="")),
            whlTrm = TRUE,
            btnCrt = NULL,
            incCmp = TRUE,
            incRcd = TRUE,
            incID = TRUE,
            incNom = TRUE,
            incOrd = TRUE,
            incNum = TRUE,
            incExc = "include",
            varSel = NULL, ...) {

            super$initialize(
                package="jTransform",
                name="jtReplace",
                requiresData=TRUE,
                ...)

            private$..varAll <- jmvcore::OptionVariables$new(
                "varAll",
                varAll,
                hidden=TRUE,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..rplTrm <- jmvcore::OptionArray$new(
                "rplTrm",
                rplTrm,
                template=jmvcore::OptionGroup$new(
                    "rplTrm",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "rplOld",
                            NULL),
                        jmvcore::OptionString$new(
                            "rplNew",
                            NULL))),
                default=list(
                    list(rplOld="", rplNew="")))
            private$..whlTrm <- jmvcore::OptionBool$new(
                "whlTrm",
                whlTrm,
                default=TRUE)
            private$..btnCrt <- jmvcore::OptionAction$new(
                "btnCrt",
                btnCrt)
            private$..incCmp <- jmvcore::OptionBool$new(
                "incCmp",
                incCmp,
                default=TRUE)
            private$..incRcd <- jmvcore::OptionBool$new(
                "incRcd",
                incRcd,
                default=TRUE)
            private$..incID <- jmvcore::OptionBool$new(
                "incID",
                incID,
                default=TRUE)
            private$..incNom <- jmvcore::OptionBool$new(
                "incNom",
                incNom,
                default=TRUE)
            private$..incOrd <- jmvcore::OptionBool$new(
                "incOrd",
                incOrd,
                default=TRUE)
            private$..incNum <- jmvcore::OptionBool$new(
                "incNum",
                incNum,
                default=TRUE)
            private$..incExc <- jmvcore::OptionList$new(
                "incExc",
                incExc,
                options=list(
                    "include",
                    "exclude"),
                default="include")
            private$..varSel <- jmvcore::OptionVariables$new(
                "varSel",
                varSel,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))

            self$.addOption(private$..varAll)
            self$.addOption(private$..rplTrm)
            self$.addOption(private$..whlTrm)
            self$.addOption(private$..btnCrt)
            self$.addOption(private$..incCmp)
            self$.addOption(private$..incRcd)
            self$.addOption(private$..incID)
            self$.addOption(private$..incNom)
            self$.addOption(private$..incOrd)
            self$.addOption(private$..incNum)
            self$.addOption(private$..incExc)
            self$.addOption(private$..varSel)
        }),
    active = list(
        varAll = function() private$..varAll$value,
        rplTrm = function() private$..rplTrm$value,
        whlTrm = function() private$..whlTrm$value,
        btnCrt = function() private$..btnCrt$value,
        incCmp = function() private$..incCmp$value,
        incRcd = function() private$..incRcd$value,
        incID = function() private$..incID$value,
        incNom = function() private$..incNom$value,
        incOrd = function() private$..incOrd$value,
        incNum = function() private$..incNum$value,
        incExc = function() private$..incExc$value,
        varSel = function() private$..varSel$value),
    private = list(
        ..varAll = NA,
        ..rplTrm = NA,
        ..whlTrm = NA,
        ..btnCrt = NA,
        ..incCmp = NA,
        ..incRcd = NA,
        ..incID = NA,
        ..incNom = NA,
        ..incOrd = NA,
        ..incNum = NA,
        ..incExc = NA,
        ..varSel = NA)
)

jtReplaceResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtReplaceResults",
    inherit = jmvcore::Group,
    active = list(
        genInf = function() private$.items[["genInf"]],
        pvwDta = function() private$.items[["pvwDta"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Replace")
            self$add(jmvcore::Html$new(
                options=options,
                name="genInf",
                clearWith=list(
                    "rplTrm",
                    "whlTrm",
                    "incCmp",
                    "incRcd",
                    "incID",
                    "incNom",
                    "incOrd",
                    "incNum",
                    "incExc",
                    "varSel",
                    "btnCrt")))
            self$add(jmvcore::Table$new(
                options=options,
                name="pvwDta",
                title="Data Preview",
                refs=list(
                    "jTransform",
                    "jmvReadWrite"),
                clearWith=list(
                    "rplTrm",
                    "whlTrm",
                    "incCmp",
                    "incRcd",
                    "incID",
                    "incNom",
                    "incOrd",
                    "incNum",
                    "incExc",
                    "varSel"),
                rows=1,
                columns=list(
                    list(
                        `name`="fstCol", 
                        `title`=""))))}))

jtReplaceBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtReplaceBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtReplace",
                version = c(1,0,0),
                options = options,
                results = jtReplaceResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Replace
#'
#' Replace Values in the Current Data Set
#'
#' @examples
#' \dontrun{
#' # the function is a wrapper for jmvReadWrite::replace_omv
#' # please use that function when in R (or in Rj)
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'}
#' @param data .
#' @param varAll .
#' @param rplTrm .
#' @param whlTrm .
#' @param btnCrt .
#' @param incCmp .
#' @param incRcd .
#' @param incID .
#' @param incNom .
#' @param incOrd .
#' @param incNum .
#' @param incExc .
#' @param varSel .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$genInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pvwDta} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pvwDta$asDF}
#'
#' \code{as.data.frame(results$pvwDta)}
#'
#' @export
jtReplace <- function(
    data,
    varAll,
    rplTrm = list(
                list(rplOld="", rplNew="")),
    whlTrm = TRUE,
    btnCrt,
    incCmp = TRUE,
    incRcd = TRUE,
    incID = TRUE,
    incNom = TRUE,
    incOrd = TRUE,
    incNum = TRUE,
    incExc = "include",
    varSel) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtReplace requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varAll)) varAll <- jmvcore::resolveQuo(jmvcore::enquo(varAll))
    if ( ! missing(varSel)) varSel <- jmvcore::resolveQuo(jmvcore::enquo(varSel))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varAll), varAll, NULL),
            `if`( ! missing(varSel), varSel, NULL))


    options <- jtReplaceOptions$new(
        varAll = varAll,
        rplTrm = rplTrm,
        whlTrm = whlTrm,
        btnCrt = btnCrt,
        incCmp = incCmp,
        incRcd = incRcd,
        incID = incID,
        incNom = incNom,
        incOrd = incOrd,
        incNum = incNum,
        incExc = incExc,
        varSel = varSel)

    analysis <- jtReplaceClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

