
# This file is automatically generated, you probably don't want to edit this

jtSearchOptions <- if (requireNamespace("jmvcore", quietly = TRUE)) R6::R6Class(
    "jtSearchOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varAll = NULL,
            srcCst = "",
            srcTrm = "",
            ignCse = FALSE,
            whlTrm = FALSE,
            shwHlp = FALSE,
            incCmp = TRUE,
            incRcd = TRUE,
            incID = TRUE,
            incNom = TRUE,
            incOrd = TRUE,
            incNum = TRUE,
            jxfLog = FALSE, ...) {

            super$initialize(
                package = "jTransform",
                name = "jtSearch",
                requiresData = TRUE,
                ...)

            private$..varAll <- jmvcore::OptionVariables$new(
                "varAll",
                varAll,
                hidden = TRUE,
                permitted = list(
                    "numeric",
                    "factor",
                    "id"),
                default = NULL)
            private$..srcCst <- jmvcore::OptionString$new(
                "srcCst",
                srcCst,
                default = "",
                hidden = TRUE)
            private$..srcTrm <- jmvcore::OptionString$new(
                "srcTrm",
                srcTrm,
                default = "",
                hidden = TRUE)
            private$..ignCse <- jmvcore::OptionBool$new(
                "ignCse",
                ignCse,
                default = FALSE)
            private$..whlTrm <- jmvcore::OptionBool$new(
                "whlTrm",
                whlTrm,
                default = FALSE)
            private$..shwHlp <- jmvcore::OptionBool$new(
                "shwHlp",
                shwHlp,
                default = FALSE)
            private$..incCmp <- jmvcore::OptionBool$new(
                "incCmp",
                incCmp,
                default = TRUE)
            private$..incRcd <- jmvcore::OptionBool$new(
                "incRcd",
                incRcd,
                default = TRUE)
            private$..incID <- jmvcore::OptionBool$new(
                "incID",
                incID,
                default = TRUE)
            private$..incNom <- jmvcore::OptionBool$new(
                "incNom",
                incNom,
                default = TRUE)
            private$..incOrd <- jmvcore::OptionBool$new(
                "incOrd",
                incOrd,
                default = TRUE)
            private$..incNum <- jmvcore::OptionBool$new(
                "incNum",
                incNum,
                default = TRUE)
            private$..jxfLog <- jmvcore::OptionBool$new(
                "jxfLog",
                jxfLog,
                hidden = TRUE,
                default = FALSE)

            self$.addOption(private$..varAll)
            self$.addOption(private$..srcCst)
            self$.addOption(private$..srcTrm)
            self$.addOption(private$..ignCse)
            self$.addOption(private$..whlTrm)
            self$.addOption(private$..shwHlp)
            self$.addOption(private$..incCmp)
            self$.addOption(private$..incRcd)
            self$.addOption(private$..incID)
            self$.addOption(private$..incNom)
            self$.addOption(private$..incOrd)
            self$.addOption(private$..incNum)
            self$.addOption(private$..jxfLog)
        }),
    active = list(
        varAll = function() private$..varAll$value,
        srcCst = function() private$..srcCst$value,
        srcTrm = function() private$..srcTrm$value,
        ignCse = function() private$..ignCse$value,
        whlTrm = function() private$..whlTrm$value,
        shwHlp = function() private$..shwHlp$value,
        incCmp = function() private$..incCmp$value,
        incRcd = function() private$..incRcd$value,
        incID = function() private$..incID$value,
        incNom = function() private$..incNom$value,
        incOrd = function() private$..incOrd$value,
        incNum = function() private$..incNum$value,
        jxfLog = function() private$..jxfLog$value),
    private = list(
        ..varAll = NA,
        ..srcCst = NA,
        ..srcTrm = NA,
        ..ignCse = NA,
        ..whlTrm = NA,
        ..shwHlp = NA,
        ..incCmp = NA,
        ..incRcd = NA,
        ..incID = NA,
        ..incNom = NA,
        ..incOrd = NA,
        ..incNum = NA,
        ..jxfLog = NA)
)

jtSearchResults <- if (requireNamespace("jmvcore", quietly = TRUE)) R6::R6Class(
    "jtSearchResults",
    inherit = jmvcore::Group,
    active = list(
        genInf = function() private$.items[["genInf"]],
        srcRes = function() private$.items[["srcRes"]]),
    private = list(),
    public = list(
        initialize = function(options) {
            super$initialize(
                options = options,
                name = "",
                title = "Search")
            self$add(jmvcore::Html$new(
                options = options,
                name = "genInf",
                visible = "(shwHlp)",
                clearWith = list(),
                content = "Please type the term to be search for into the text box. If you want that partial matches (i.e., the search term appears within values) are found, leave the tick box \"Whole Word\" unset.</p> <p>The <strong>\"Include / Exclude\"</strong> collapse box permits to specifically select in which column and measurement types the <strong> search</strong> shall be conducted. Ticking the check boxes includes that variable or measurement type.\n"))
            self$add(jmvcore::Html$new(
                options = options,
                name = "srcRes",
                clearWith = list(
                    "varAll",
                    "srcTrm",
                    "ignCse",
                    "whlTrm",
                    "incCmp",
                    "incRcd",
                    "incID",
                    "incNom",
                    "incOrd",
                    "incNum"),
                refs = list(
                    "jTransform",
                    "jmvReadWrite")))}))

jtSearchBase <- if (requireNamespace("jmvcore", quietly = TRUE)) R6::R6Class(
    "jtSearchBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data = NULL, datasetId = "", analysisId = "", revision = 0) {
            super$initialize(
                package = "jTransform",
                name = "jtSearch",
                version = c(1, 0, 0),
                options = options,
                results = jtSearchResults$new(options = options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = "auto")
        }))

#" Search
#'
#" Search Within the Current Data Set
#'
#" @examples
#" \donttest{
#" # the function is a wrapper for jmvReadWrite::search_omv
#" # please use that function when in R (or in Rj)
#" # for more information: https://sjentsch.github.io/jmvReadWrite
#'}
#" @param data .
#" @param varAll .
#" @param srcCst .
#" @param srcTrm .
#" @param ignCse .
#" @param whlTrm .
#" @param shwHlp .
#" @param incCmp .
#" @param incRcd .
#" @param incID .
#" @param incNom .
#" @param incOrd .
#" @param incNum .
#" @param jxfLog .
#" @return A results object containing:
#" \tabular{llllll}{
#"   \code{results$genInf} \tab \tab \tab \tab \tab a html \cr
#"   \code{results$srcRes} \tab \tab \tab \tab \tab a html \cr
#" }
#'
#" @export
jtSearch <- function(
    data,
    varAll = NULL,
    srcCst = "",
    srcTrm = "",
    ignCse = FALSE,
    whlTrm = FALSE,
    shwHlp = FALSE,
    incCmp = TRUE,
    incRcd = TRUE,
    incID = TRUE,
    incNom = TRUE,
    incOrd = TRUE,
    incNum = TRUE,
    jxfLog = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly = TRUE))
        stop("jtSearch requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varAll)) varAll <- jmvcore::resolveQuo(jmvcore::enquo(varAll))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varAll), varAll, NULL))


    options <- jtSearchOptions$new(
        varAll = varAll,
        srcCst = srcCst,
        srcTrm = srcTrm,
        ignCse = ignCse,
        whlTrm = whlTrm,
        shwHlp = shwHlp,
        incCmp = incCmp,
        incRcd = incRcd,
        incID = incID,
        incNom = incNom,
        incOrd = incOrd,
        incNum = incNum,
        jxfLog = jxfLog)

    analysis <- jtSearchClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
