
# This file is automatically generated, you probably don't want to edit this

jtSortOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtSortOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varSrt = NULL,
            varOth = NULL,
            ordSrt = NULL,
            fleOut = "Dataset_sort.omv",
            btnOut = NULL,
            blnOut = FALSE, ...) {

            super$initialize(
                package="jTransform",
                name="jtSort",
                requiresData=TRUE,
                ...)

            private$..varSrt <- jmvcore::OptionVariables$new(
                "varSrt",
                varSrt,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..varOth <- jmvcore::OptionVariables$new(
                "varOth",
                varOth,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..ordSrt <- jmvcore::OptionArray$new(
                "ordSrt",
                ordSrt,
                items="(varSrt)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "ordSrt",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "order",
                            NULL,
                            options=list(
                                "ascend",
                                "descend")))))
            private$..fleOut <- jmvcore::OptionString$new(
                "fleOut",
                fleOut,
                default="Dataset_sort.omv")
            private$..btnOut <- jmvcore::OptionString$new(
                "btnOut",
                btnOut,
                hidden=TRUE)
            private$..blnOut <- jmvcore::OptionBool$new(
                "blnOut",
                blnOut,
                default=FALSE,
                hidden=TRUE)

            self$.addOption(private$..varSrt)
            self$.addOption(private$..varOth)
            self$.addOption(private$..ordSrt)
            self$.addOption(private$..fleOut)
            self$.addOption(private$..btnOut)
            self$.addOption(private$..blnOut)
        }),
    active = list(
        varSrt = function() private$..varSrt$value,
        varOth = function() private$..varOth$value,
        ordSrt = function() private$..ordSrt$value,
        fleOut = function() private$..fleOut$value,
        btnOut = function() private$..btnOut$value,
        blnOut = function() private$..blnOut$value),
    private = list(
        ..varSrt = NA,
        ..varOth = NA,
        ..ordSrt = NA,
        ..fleOut = NA,
        ..btnOut = NA,
        ..blnOut = NA)
)

jtSortResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtSortResults",
    inherit = jmvcore::Group,
    active = list(
        txtHdr = function() private$.items[["txtHdr"]],
        txtOut = function() private$.items[["txtOut"]],
        txtPvw = function() private$.items[["txtPvw"]],
        txtInf = function() private$.items[["txtInf"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sort data set")
            self$add(jmvcore::Html$new(
                options=options,
                name="txtHdr",
                refs="jmvReadWrite",
                content="<h2>This function sorts a dataset after one or more variables.</h2>\n"))
            self$add(jmvcore::Html$new(
                options=options,
                name="txtOut",
                content=""))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="txtPvw",
                title="Preview of the output"))
            self$add(jmvcore::Html$new(
                options=options,
                name="txtInf",
                content="<h2>More detailed explanation</h2> <p>Please assign one or more variables to the variable box \u201CVariable(s) to be sorted after\u201D. The order in which the variables appear in the variable box determines after which variable is sorted first (one could, e.g., first sort after gender and afterwards after age).</p> <p>Variables are sorted in ascending order (as default), but you can change the order if desired.</p> <p>Currently, the remaining variables (i.e., those not to be used for sorting but to be included into the output file) have to be assigned to \u201CFurther variables in the output\u201D.</p>\n"))}))

jtSortBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtSortBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtSort",
                version = c(1,0,0),
                options = options,
                results = jtSortResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Sort data set
#'
#' Sort data set
#'
#' @examples
#' # the function is a wrapper for jmvReadWrite::sort_omv
#' # please use that function when using R
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'
#' @param data the data as a data frame
#' @param varSrt a vector of strings naming the variables to sort \code{data}
#'   with
#' @param varOth .
#' @param ordSrt a list of lists specifying the order with which variables are
#'   sorted, either \code{'ascending'}, or \code{'descending'}
#' @param fleOut a string with name and location of the output file (the home
#'   directory, if no directory is given)
#' @param btnOut .
#' @param blnOut .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$txtHdr} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$txtOut} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$txtPvw} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$txtInf} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
jtSort <- function(
    data,
    varSrt,
    varOth,
    ordSrt = NULL,
    fleOut = "Dataset_sort.omv",
    btnOut,
    blnOut = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtSort requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varSrt)) varSrt <- jmvcore::resolveQuo(jmvcore::enquo(varSrt))
    if ( ! missing(varOth)) varOth <- jmvcore::resolveQuo(jmvcore::enquo(varOth))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varSrt), varSrt, NULL),
            `if`( ! missing(varOth), varOth, NULL))


    options <- jtSortOptions$new(
        varSrt = varSrt,
        varOth = varOth,
        ordSrt = ordSrt,
        fleOut = fleOut,
        btnOut = btnOut,
        blnOut = blnOut)

    analysis <- jtSortClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

