
# This file is automatically generated, you probably don't want to edit this

jtSortOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtSortOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varSrt = NULL,
            varAll = NULL,
            ordSrt = NULL,
            btnCrt = NULL, ...) {

            super$initialize(
                package="jTransform",
                name="jtSort",
                requiresData=TRUE,
                ...)

            private$..varSrt <- jmvcore::OptionVariables$new(
                "varSrt",
                varSrt,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..varAll <- jmvcore::OptionVariables$new(
                "varAll",
                varAll,
                hidden=TRUE,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..ordSrt <- jmvcore::OptionArray$new(
                "ordSrt",
                ordSrt,
                items="(varSrt)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "ordSrt",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "order",
                            NULL,
                            options=list(
                                "ascend",
                                "descend")))))
            private$..btnCrt <- jmvcore::OptionAction$new(
                "btnCrt",
                btnCrt)

            self$.addOption(private$..varSrt)
            self$.addOption(private$..varAll)
            self$.addOption(private$..ordSrt)
            self$.addOption(private$..btnCrt)
        }),
    active = list(
        varSrt = function() private$..varSrt$value,
        varAll = function() private$..varAll$value,
        ordSrt = function() private$..ordSrt$value,
        btnCrt = function() private$..btnCrt$value),
    private = list(
        ..varSrt = NA,
        ..varAll = NA,
        ..ordSrt = NA,
        ..btnCrt = NA)
)

jtSortResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtSortResults",
    inherit = jmvcore::Group,
    active = list(
        genInf = function() private$.items[["genInf"]],
        pvwDta = function() private$.items[["pvwDta"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sort data set")
            self$add(jmvcore::Html$new(
                options=options,
                name="genInf",
                clearWith=list(
                    "varSrt",
                    "varAll",
                    "btnCrt")))
            self$add(jmvcore::Table$new(
                options=options,
                name="pvwDta",
                title="Data Preview",
                refs=list(
                    "jTransform",
                    "jmvReadWrite"),
                clearWith=list(
                    "varSrt",
                    "varAll",
                    "ordSrt"),
                rows=1,
                columns=list(
                    list(
                        `name`="fstCol", 
                        `title`=""))))}))

jtSortBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtSortBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtSort",
                version = c(1,0,0),
                options = options,
                results = jtSortResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Sort data set
#'
#' Sort data set
#'
#' @examples
#' \dontrun{
#' # the function is a wrapper for jmvReadWrite::sort_omv
#' # please use that function when in R (or in Rj)
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'}
#' @param data .
#' @param varSrt .
#' @param varAll .
#' @param ordSrt .
#' @param btnCrt .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$genInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pvwDta} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pvwDta$asDF}
#'
#' \code{as.data.frame(results$pvwDta)}
#'
#' @export
jtSort <- function(
    data,
    varSrt,
    varAll,
    ordSrt = NULL,
    btnCrt) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtSort requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varSrt)) varSrt <- jmvcore::resolveQuo(jmvcore::enquo(varSrt))
    if ( ! missing(varAll)) varAll <- jmvcore::resolveQuo(jmvcore::enquo(varAll))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varSrt), varSrt, NULL),
            `if`( ! missing(varAll), varAll, NULL))


    options <- jtSortOptions$new(
        varSrt = varSrt,
        varAll = varAll,
        ordSrt = ordSrt,
        btnCrt = btnCrt)

    analysis <- jtSortClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

