
# This file is automatically generated, you probably don't want to edit this

jtTransformVarsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtTransformVarsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varAll = NULL,
            posSqr = NULL,
            negSqr = NULL,
            posLog = NULL,
            negLog = NULL,
            posInv = NULL,
            negInv = NULL,
            shwHlp = TRUE,
            btnCrt = FALSE, ...) {

            super$initialize(
                package="jTransform",
                name="jtTransformVars",
                requiresData=TRUE,
                ...)

            private$..varAll <- jmvcore::OptionVariables$new(
                "varAll",
                varAll,
                hidden=TRUE,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                default=NULL)
            private$..posSqr <- jmvcore::OptionVariables$new(
                "posSqr",
                posSqr,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..negSqr <- jmvcore::OptionVariables$new(
                "negSqr",
                negSqr,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..posLog <- jmvcore::OptionVariables$new(
                "posLog",
                posLog,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..negLog <- jmvcore::OptionVariables$new(
                "negLog",
                negLog,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..posInv <- jmvcore::OptionVariables$new(
                "posInv",
                posInv,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..negInv <- jmvcore::OptionVariables$new(
                "negInv",
                negInv,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..shwHlp <- jmvcore::OptionBool$new(
                "shwHlp",
                shwHlp,
                default=TRUE)
            private$..btnCrt <- jmvcore::OptionAction$new(
                "btnCrt",
                btnCrt,
                default=FALSE)

            self$.addOption(private$..varAll)
            self$.addOption(private$..posSqr)
            self$.addOption(private$..negSqr)
            self$.addOption(private$..posLog)
            self$.addOption(private$..negLog)
            self$.addOption(private$..posInv)
            self$.addOption(private$..negInv)
            self$.addOption(private$..shwHlp)
            self$.addOption(private$..btnCrt)
        }),
    active = list(
        varAll = function() private$..varAll$value,
        posSqr = function() private$..posSqr$value,
        negSqr = function() private$..negSqr$value,
        posLog = function() private$..posLog$value,
        negLog = function() private$..negLog$value,
        posInv = function() private$..posInv$value,
        negInv = function() private$..negInv$value,
        shwHlp = function() private$..shwHlp$value,
        btnCrt = function() private$..btnCrt$value),
    private = list(
        ..varAll = NA,
        ..posSqr = NA,
        ..negSqr = NA,
        ..posLog = NA,
        ..negLog = NA,
        ..posInv = NA,
        ..negInv = NA,
        ..shwHlp = NA,
        ..btnCrt = NA)
)

jtTransformVarsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtTransformVarsResults",
    inherit = jmvcore::Group,
    active = list(
        genInf = function() private$.items[["genInf"]],
        dtaInf = function() private$.items[["dtaInf"]],
        pvwDta = function() private$.items[["pvwDta"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Transform (Reduce Skewness)")
            self$add(jmvcore::Html$new(
                options=options,
                name="genInf",
                visible="(shwHlp)",
                clearWith=list(),
                content="Please assign at least one variable to at least one of the variable boxes indicating what (approximate) degree (moderate, strong, extreme and kind (postive or negative) of skewness this variable has. For moderately skewed variables, a square-root-transformation is used, for strongly skewed variables, a logarithic transformation, and for severly skewed variables an inversion. If necessary, a constant is added (automatically) in order to avoid the transformation returning NA-values.</p> <p>NB: The transformations work only for numeric variables (integer or decimal); please adjust the measure / data type if necessary.\n"))
            self$add(jmvcore::Html$new(
                options=options,
                name="dtaInf",
                clearWith=list(
                    "varDst",
                    "clmDst",
                    "btnCrt"),
                content=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="pvwDta",
                title="Data Preview",
                refs=list(
                    "jTransform",
                    "jmvReadWrite"),
                clearWith=list(
                    "varOrd",
                    "blnAll"),
                rows=1,
                columns=list(
                    list(
                        `name`="fstCol", 
                        `title`=""))))}))

jtTransformVarsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtTransformVarsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtTransformVars",
                version = c(1,0,0),
                options = options,
                results = jtTransformVarsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Transform (Reduce Skewness)
#'
#' Create New (Computed) Variables, Aiming At Reducing Deviations From A 
#' Normal Distribution
#'
#' @examples
#' \donttest{
#' # the function is a wrapper for jmvReadWrite::transform_vars_omv
#' # please use that function when in R (or in Rj)
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'}
#' @param data .
#' @param varAll .
#' @param posSqr .
#' @param negSqr .
#' @param posLog .
#' @param negLog .
#' @param posInv .
#' @param negInv .
#' @param shwHlp .
#' @param btnCrt .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$genInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dtaInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pvwDta} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pvwDta$asDF}
#'
#' \code{as.data.frame(results$pvwDta)}
#'
#' @export
jtTransformVars <- function(
    data,
    varAll = NULL,
    posSqr = NULL,
    negSqr = NULL,
    posLog = NULL,
    negLog = NULL,
    posInv = NULL,
    negInv = NULL,
    shwHlp = TRUE,
    btnCrt = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtTransformVars requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varAll)) varAll <- jmvcore::resolveQuo(jmvcore::enquo(varAll))
    if ( ! missing(posSqr)) posSqr <- jmvcore::resolveQuo(jmvcore::enquo(posSqr))
    if ( ! missing(negSqr)) negSqr <- jmvcore::resolveQuo(jmvcore::enquo(negSqr))
    if ( ! missing(posLog)) posLog <- jmvcore::resolveQuo(jmvcore::enquo(posLog))
    if ( ! missing(negLog)) negLog <- jmvcore::resolveQuo(jmvcore::enquo(negLog))
    if ( ! missing(posInv)) posInv <- jmvcore::resolveQuo(jmvcore::enquo(posInv))
    if ( ! missing(negInv)) negInv <- jmvcore::resolveQuo(jmvcore::enquo(negInv))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varAll), varAll, NULL),
            `if`( ! missing(posSqr), posSqr, NULL),
            `if`( ! missing(negSqr), negSqr, NULL),
            `if`( ! missing(posLog), posLog, NULL),
            `if`( ! missing(negLog), negLog, NULL),
            `if`( ! missing(posInv), posInv, NULL),
            `if`( ! missing(negInv), negInv, NULL))


    options <- jtTransformVarsOptions$new(
        varAll = varAll,
        posSqr = posSqr,
        negSqr = negSqr,
        posLog = posLog,
        negLog = negLog,
        posInv = posInv,
        negInv = negInv,
        shwHlp = shwHlp,
        btnCrt = btnCrt)

    analysis <- jtTransformVarsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

