
# This file is automatically generated, you probably don't want to edit this

jttransposeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jttransposeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varNames = NULL,
            varTarget = NULL,
            btnOut = NULL, ...) {

            super$initialize(
                package="jTransform",
                name="jttranspose",
                requiresData=TRUE,
                ...)

            private$..varNames <- jmvcore::OptionVariable$new(
                "varNames",
                varNames,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                required=FALSE)
            private$..varTarget <- jmvcore::OptionVariables$new(
                "varTarget",
                varTarget,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                required=TRUE)
            private$..btnOut <- jmvcore::OptionAction$new(
                "btnOut",
                btnOut)

            self$.addOption(private$..varNames)
            self$.addOption(private$..varTarget)
            self$.addOption(private$..btnOut)
        }),
    active = list(
        varNames = function() private$..varNames$value,
        varTarget = function() private$..varTarget$value,
        btnOut = function() private$..btnOut$value),
    private = list(
        ..varNames = NA,
        ..varTarget = NA,
        ..btnOut = NA)
)

jttransposeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jttransposeResults",
    inherit = jmvcore::Group,
    active = list(
        help = function() private$.items[["help"]],
        desc = function() private$.items[["desc"]],
        info = function() private$.items[["info"]],
        showdata = function() private$.items[["showdata"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Transpose the dataset")
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                visible=TRUE,
                clearWith=list(
                    "varTarget",
                    "varNames",
                    "btnOut")))
            self$add(jmvcore::Html$new(
                options=options,
                name="desc",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Info Table",
                refs=list(
                    "jTransform",
                    "jmvReadWrite"),
                clearWith=list(
                    "varTarget",
                    "varNames"),
                columns=list(
                    list(
                        `name`="text", 
                        `title`="Info", 
                        `type`="text"),
                    list(
                        `name`="var", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="showdata",
                title="Data Preview",
                clearWith=list(
                    "varTarget",
                    "varNames"),
                columns=list(
                    list(
                        `name`="row", 
                        `title`="Rows", 
                        `type`="integer"))))}))

jttransposeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jttransposeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jttranspose",
                version = c(1,0,0),
                options = options,
                results = jttransposeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Transpose the dataset
#'
#' Transpose the dataset
#'
#' @examples
#' \dontrun{
#' # the function is a wrapper for jmvReadWrite::transpose_omv
#' # please use that function when in R (or in Rj)
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'}
#' @param data the data as a data frame
#' @param varNames .
#' @param varTarget .
#' @param btnOut .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$showdata} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
jttranspose <- function(
    data,
    varNames,
    varTarget,
    btnOut) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jttranspose requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varNames)) varNames <- jmvcore::resolveQuo(jmvcore::enquo(varNames))
    if ( ! missing(varTarget)) varTarget <- jmvcore::resolveQuo(jmvcore::enquo(varTarget))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varNames), varNames, NULL),
            `if`( ! missing(varTarget), varTarget, NULL))


    options <- jttransposeOptions$new(
        varNames = varNames,
        varTarget = varTarget,
        btnOut = btnOut)

    analysis <- jttransposeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

