
# This file is automatically generated, you probably don't want to edit this

jtTransposeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtTransposeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varNme = NULL,
            varOth = NULL,
            btnCrt = FALSE, ...) {

            super$initialize(
                package="jTransform",
                name="jtTranspose",
                requiresData=TRUE,
                ...)

            private$..varNme <- jmvcore::OptionVariable$new(
                "varNme",
                varNme,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                required=FALSE,
                default=NULL)
            private$..varOth <- jmvcore::OptionVariables$new(
                "varOth",
                varOth,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                required=TRUE,
                default=NULL)
            private$..btnCrt <- jmvcore::OptionAction$new(
                "btnCrt",
                btnCrt,
                default=FALSE)

            self$.addOption(private$..varNme)
            self$.addOption(private$..varOth)
            self$.addOption(private$..btnCrt)
        }),
    active = list(
        varNme = function() private$..varNme$value,
        varOth = function() private$..varOth$value,
        btnCrt = function() private$..btnCrt$value),
    private = list(
        ..varNme = NA,
        ..varOth = NA,
        ..btnCrt = NA)
)

jtTransposeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtTransposeResults",
    inherit = jmvcore::Group,
    active = list(
        genInf = function() private$.items[["genInf"]],
        pvwDta = function() private$.items[["pvwDta"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Transpose")
            self$add(jmvcore::Html$new(
                options=options,
                name="genInf",
                clearWith=list(
                    "varNme",
                    "varOth",
                    "btnCrt")))
            self$add(jmvcore::Table$new(
                options=options,
                name="pvwDta",
                title="Data Preview",
                refs=list(
                    "jTransform",
                    "jmvReadWrite"),
                clearWith=list(
                    "varNme",
                    "varOth"),
                rows=1,
                columns=list(
                    list(
                        `name`="fstCol", 
                        `title`=""))))}))

jtTransposeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtTransposeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtTranspose",
                version = c(1,0,0),
                options = options,
                results = jtTransposeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Transpose
#'
#' Transpose a Data Set
#'
#' @examples
#' \dontrun{
#' # the function is a wrapper for jmvReadWrite::transpose_omv
#' # please use that function when in R (or in Rj)
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'}
#' @param data .
#' @param varNme .
#' @param varOth .
#' @param btnCrt .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$genInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pvwDta} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pvwDta$asDF}
#'
#' \code{as.data.frame(results$pvwDta)}
#'
#' @export
jtTranspose <- function(
    data,
    varNme = NULL,
    varOth = NULL,
    btnCrt = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtTranspose requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varNme)) varNme <- jmvcore::resolveQuo(jmvcore::enquo(varNme))
    if ( ! missing(varOth)) varOth <- jmvcore::resolveQuo(jmvcore::enquo(varOth))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varNme), varNme, NULL),
            `if`( ! missing(varOth), varOth, NULL))


    options <- jtTransposeOptions$new(
        varNme = varNme,
        varOth = varOth,
        btnCrt = btnCrt)

    analysis <- jtTransposeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

