
# This file is automatically generated, you probably don't want to edit this

jtTransposeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtTransposeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varNme = NULL,
            varOth = NULL,
            btnOut = NULL,
            blnOut = FALSE, ...) {

            super$initialize(
                package="jTransform",
                name="jtTranspose",
                requiresData=TRUE,
                ...)

            private$..varNme <- jmvcore::OptionVariable$new(
                "varNme",
                varNme,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                required=FALSE)
            private$..varOth <- jmvcore::OptionVariables$new(
                "varOth",
                varOth,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                required=TRUE)
            private$..btnOut <- jmvcore::OptionString$new(
                "btnOut",
                btnOut,
                hidden=TRUE)
            private$..blnOut <- jmvcore::OptionBool$new(
                "blnOut",
                blnOut,
                default=FALSE,
                hidden=TRUE)

            self$.addOption(private$..varNme)
            self$.addOption(private$..varOth)
            self$.addOption(private$..btnOut)
            self$.addOption(private$..blnOut)
        }),
    active = list(
        varNme = function() private$..varNme$value,
        varOth = function() private$..varOth$value,
        btnOut = function() private$..btnOut$value,
        blnOut = function() private$..blnOut$value),
    private = list(
        ..varNme = NA,
        ..varOth = NA,
        ..btnOut = NA,
        ..blnOut = NA)
)

jtTransposeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtTransposeResults",
    inherit = jmvcore::Group,
    active = list(
        txtPvw = function() private$.items[["txtPvw"]],
        txtInf = function() private$.items[["txtInf"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Transpose the dataset")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="txtPvw",
                title="Outout Preview"))
            self$add(jmvcore::Html$new(
                options=options,
                name="txtInf",
                refs="jTransform, jmvReadWrite",
                content="<h2>Details</h2> <p><strong>This function transposes a dataset (i.e., rows are made into columns and columns into rows).</strong></p> <p>Please assign maximally one variable to the variable box \u201CVariable with column names for the output\u201D (this variable might contain names of trials or questionnaire items). If you leave the box empty, generic variable names are generated (\u201CV_...\u201D).</p> <p>The variables to be transposed (i.e., those to become rows in your output data set) have to be assigned to \u201CVariables to be transposed\u201D.</p>\n"))}))

jtTransposeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtTransposeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtTranspose",
                version = c(1,0,0),
                options = options,
                results = jtTransposeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Transpose the dataset
#'
#' Transpose the dataset
#'
#' @examples
#' \dontrun{
#' # the function is a wrapper for jmvReadWrite::transpose_omv
#' # please use that function when using R
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'}
#' @param data the data as a data frame
#' @param varNme .
#' @param varOth .
#' @param btnOut .
#' @param blnOut .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$txtPvw} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$txtInf} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
jtTranspose <- function(
    data,
    varNme,
    varOth,
    btnOut,
    blnOut = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtTranspose requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varNme)) varNme <- jmvcore::resolveQuo(jmvcore::enquo(varNme))
    if ( ! missing(varOth)) varOth <- jmvcore::resolveQuo(jmvcore::enquo(varOth))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varNme), varNme, NULL),
            `if`( ! missing(varOth), varOth, NULL))


    options <- jtTransposeOptions$new(
        varNme = varNme,
        varOth = varOth,
        btnOut = btnOut,
        blnOut = blnOut)

    analysis <- jtTransposeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

