
# This file is automatically generated, you probably don't want to edit this

jtWide2LongOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtWide2LongOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            chcEnI = "excluded",
            varEnI = NULL,
            varID = NULL,
            varTme = "cond",
            varSep = "_",
            varOrd = "times",
            fleOut = "Dataset_wide.omv",
            btnOut = NULL,
            blnOut = FALSE, ...) {

            super$initialize(
                package="jTransform",
                name="jtWide2Long",
                requiresData=TRUE,
                ...)

            private$..chcEnI <- jmvcore::OptionList$new(
                "chcEnI",
                chcEnI,
                options=list(
                    "excluded",
                    "included"),
                default="excluded")
            private$..varEnI <- jmvcore::OptionVariables$new(
                "varEnI",
                varEnI,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..varID <- jmvcore::OptionVariables$new(
                "varID",
                varID,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..varTme <- jmvcore::OptionString$new(
                "varTme",
                varTme,
                default="cond")
            private$..varSep <- jmvcore::OptionString$new(
                "varSep",
                varSep,
                default="_")
            private$..varOrd <- jmvcore::OptionList$new(
                "varOrd",
                varOrd,
                options=list(
                    "times",
                    "variables"),
                default="times")
            private$..fleOut <- jmvcore::OptionString$new(
                "fleOut",
                fleOut,
                default="Dataset_wide.omv")
            private$..btnOut <- jmvcore::OptionString$new(
                "btnOut",
                btnOut,
                hidden=TRUE)
            private$..blnOut <- jmvcore::OptionBool$new(
                "blnOut",
                blnOut,
                default=FALSE,
                hidden=TRUE)

            self$.addOption(private$..chcEnI)
            self$.addOption(private$..varEnI)
            self$.addOption(private$..varID)
            self$.addOption(private$..varTme)
            self$.addOption(private$..varSep)
            self$.addOption(private$..varOrd)
            self$.addOption(private$..fleOut)
            self$.addOption(private$..btnOut)
            self$.addOption(private$..blnOut)
        }),
    active = list(
        chcEnI = function() private$..chcEnI$value,
        varEnI = function() private$..varEnI$value,
        varID = function() private$..varID$value,
        varTme = function() private$..varTme$value,
        varSep = function() private$..varSep$value,
        varOrd = function() private$..varOrd$value,
        fleOut = function() private$..fleOut$value,
        btnOut = function() private$..btnOut$value,
        blnOut = function() private$..blnOut$value),
    private = list(
        ..chcEnI = NA,
        ..varEnI = NA,
        ..varID = NA,
        ..varTme = NA,
        ..varSep = NA,
        ..varOrd = NA,
        ..fleOut = NA,
        ..btnOut = NA,
        ..blnOut = NA)
)

jtWide2LongResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtWide2LongResults",
    inherit = jmvcore::Group,
    active = list(
        txtInf = function() private$.items[["txtInf"]],
        txtOut = function() private$.items[["txtOut"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Transform dataset from wide to long")
            self$add(jmvcore::Html$new(
                options=options,
                name="txtInf",
                title="",
                content="Trial text"))
            self$add(jmvcore::Html$new(
                options=options,
                name="txtOut",
                title="",
                content=""))}))

jtWide2LongBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jtWide2LongBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "jtWide2Long",
                version = c(1,0,0),
                options = options,
                results = jtWide2LongResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Transform dataset from wide to long
#'
#' Transform dataset from wide to long
#'
#' @examples
#' # the function is a wrapper for jmvReadWrite::wide2long_omv
#' # please use that function when using R
#' # for more information: https://sjentsch.github.io/jmvReadWrite
#'
#' @param data the data as a data frame
#' @param chcEnI a string (either "excluded" [default] or "included")
#'   determining how to treat the entries of the variable list (varEnI)
#' @param varEnI if chcEnI is "excluded" and this variable list is empty
#'   (i.e., no variables are excluded) then all variables are included; if
#'   chcEnI is "excluded" and this variable list contains entries then varID,
#'   varTme and all variables except those on this list are included; if chcEnI
#'   is "included" then varID, varTme and all variables on this list are
#'   included
#' @param varID a vector of strings containing the names of the variables that
#'   identify the same unit (e.g., an individual, a group, an organization,
#'   etc.)
#' @param varTme variable that (is created to) differentiates multiple records
#'   from the same unit (e.g., an individual, a group, an organization, etc.);
#'   default: "cond", a counter is added for each time-varying part
#' @param varSep separator character between the fixed and the time-varying
#'   part of the variable name ("VAR1_1", "VAR1_2"; default: "_")
#' @param varOrd a string (either "times" or "vars") describing how variables
#'   / columns are organized: for "times" (default) the steps of the time
#'   varying variable are adjacent, for "vars" the steps of the original columns
#'   in the long dataset
#' @param fleOut a string with name and location of the output file (the home
#'   directory, if no directory is given)
#' @param btnOut .
#' @param blnOut .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$txtInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$txtOut} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
jtWide2Long <- function(
    data,
    chcEnI = "excluded",
    varEnI,
    varID,
    varTme = "cond",
    varSep = "_",
    varOrd = "times",
    fleOut = "Dataset_wide.omv",
    btnOut,
    blnOut = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jtWide2Long requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varEnI)) varEnI <- jmvcore::resolveQuo(jmvcore::enquo(varEnI))
    if ( ! missing(varID)) varID <- jmvcore::resolveQuo(jmvcore::enquo(varID))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varEnI), varEnI, NULL),
            `if`( ! missing(varID), varID, NULL))


    options <- jtWide2LongOptions$new(
        chcEnI = chcEnI,
        varEnI = varEnI,
        varID = varID,
        varTme = varTme,
        varSep = varSep,
        varOrd = varOrd,
        fleOut = fleOut,
        btnOut = btnOut,
        blnOut = blnOut)

    analysis <- jtWide2LongClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

