
# This file is automatically generated, you probably don't want to edit this

wide2longOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wide2longOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = "simple",
            sim_colstorows = NULL,
            sim_covs = NULL,
            sim_index = "index",
            sim_dep = "y",
            comp_colstorows = list(
                list(label="long_y", vars=list())),
            comp_index = list(
                list(var="index1", levels=0)),
            comp_covs = NULL,
            reshape = NULL, ...) {

            super$initialize(
                package="jTransform",
                name="wide2long",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "simple",
                    "complex"),
                default="simple")
            private$..sim_colstorows <- jmvcore::OptionVariables$new(
                "sim_colstorows",
                sim_colstorows)
            private$..sim_covs <- jmvcore::OptionVariables$new(
                "sim_covs",
                sim_covs)
            private$..sim_index <- jmvcore::OptionString$new(
                "sim_index",
                sim_index,
                default="index")
            private$..sim_dep <- jmvcore::OptionString$new(
                "sim_dep",
                sim_dep,
                default="y")
            private$..comp_colstorows <- jmvcore::OptionArray$new(
                "comp_colstorows",
                comp_colstorows,
                default=list(
                    list(label="long_y", vars=list())),
                template=jmvcore::OptionGroup$new(
                    "comp_colstorows",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionVariables$new(
                            "vars",
                            NULL))))
            private$..comp_index <- jmvcore::OptionArray$new(
                "comp_index",
                comp_index,
                default=list(
                    list(var="index1", levels=0)),
                template=jmvcore::OptionGroup$new(
                    "comp_index",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "var",
                            NULL),
                        jmvcore::OptionInteger$new(
                            "levels",
                            NULL))))
            private$..comp_covs <- jmvcore::OptionVariables$new(
                "comp_covs",
                comp_covs)
            private$..reshape <- jmvcore::OptionAction$new(
                "reshape",
                reshape)

            self$.addOption(private$..mode)
            self$.addOption(private$..sim_colstorows)
            self$.addOption(private$..sim_covs)
            self$.addOption(private$..sim_index)
            self$.addOption(private$..sim_dep)
            self$.addOption(private$..comp_colstorows)
            self$.addOption(private$..comp_index)
            self$.addOption(private$..comp_covs)
            self$.addOption(private$..reshape)
        }),
    active = list(
        mode = function() private$..mode$value,
        sim_colstorows = function() private$..sim_colstorows$value,
        sim_covs = function() private$..sim_covs$value,
        sim_index = function() private$..sim_index$value,
        sim_dep = function() private$..sim_dep$value,
        comp_colstorows = function() private$..comp_colstorows$value,
        comp_index = function() private$..comp_index$value,
        comp_covs = function() private$..comp_covs$value,
        reshape = function() private$..reshape$value),
    private = list(
        ..mode = NA,
        ..sim_colstorows = NA,
        ..sim_covs = NA,
        ..sim_index = NA,
        ..sim_dep = NA,
        ..comp_colstorows = NA,
        ..comp_index = NA,
        ..comp_covs = NA,
        ..reshape = NA)
)

wide2longResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wide2longResults",
    inherit = jmvcore::Group,
    active = list(
        desc = function() private$.items[["desc"]],
        help = function() private$.items[["help"]],
        info = function() private$.items[["info"]],
        features = function() private$.items[["features"]],
        showdata = function() private$.items[["showdata"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Wide to Long")
            self$add(jmvcore::Html$new(
                options=options,
                name="desc",
                title="Getting started",
                clearWith=list(
                    "mode")))
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Info Table",
                clearWith=list(
                    "sim_colstorows",
                    "comp_colstorows",
                    "sim_index",
                    "comp_index"),
                columns=list(
                    list(
                        `name`="text", 
                        `title`="Info", 
                        `type`="text"),
                    list(
                        `name`="var", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="features",
                title="Repeated measures levels",
                clearWith=list(
                    "sim_colstorows",
                    "comp_colstorows",
                    "sim_index",
                    "comp_index"),
                columns=list(
                    list(
                        `name`="Freq", 
                        `title`="Freq", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="showdata",
                title="Data Preview",
                clearWith=list(
                    "mode",
                    "sim_colstorows",
                    "sim_covs",
                    "sim_index",
                    "sim_dep",
                    "comp_colstorows",
                    "comp_index",
                    "comp_covs"),
                columns=list(
                    list(
                        `name`="row", 
                        `title`="Rows", 
                        `type`="integer"))))}))

wide2longBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wide2longBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jTransform",
                name = "wide2long",
                version = c(1,0,0),
                options = options,
                results = wide2longResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Wide to Long
#'
#' 
#' @param data .
#' @param mode .
#' @param sim_colstorows .
#' @param sim_covs .
#' @param sim_index .
#' @param sim_dep .
#' @param comp_colstorows .
#' @param comp_index .
#' @param comp_covs .
#' @param reshape .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$desc} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$features} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$showdata} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
wide2long <- function(
    data,
    mode = "simple",
    sim_colstorows,
    sim_covs,
    sim_index = "index",
    sim_dep = "y",
    comp_colstorows = list(
                list(label="long_y", vars=list())),
    comp_index = list(
                list(var="index1", levels=0)),
    comp_covs,
    reshape) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("wide2long requires jmvcore to be installed (restart may be required)")

    if ( ! missing(sim_colstorows)) sim_colstorows <- jmvcore::resolveQuo(jmvcore::enquo(sim_colstorows))
    if ( ! missing(sim_covs)) sim_covs <- jmvcore::resolveQuo(jmvcore::enquo(sim_covs))
    if ( ! missing(comp_covs)) comp_covs <- jmvcore::resolveQuo(jmvcore::enquo(comp_covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(sim_colstorows), sim_colstorows, NULL),
            `if`( ! missing(sim_covs), sim_covs, NULL),
            `if`( ! missing(comp_covs), comp_covs, NULL))


    options <- wide2longOptions$new(
        mode = mode,
        sim_colstorows = sim_colstorows,
        sim_covs = sim_covs,
        sim_index = sim_index,
        sim_dep = sim_dep,
        comp_colstorows = comp_colstorows,
        comp_index = comp_index,
        comp_covs = comp_covs,
        reshape = reshape)

    analysis <- wide2longClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

